### ISSUE TITLE
gitlab - issue applyGitlabTerraform not working

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1013]
Cloud install - gitlab failing

# Output

```bash 
- Gitlab available at http://localhost:8888
- Gitlab setup tokens
- Gitlab terraform
Setup Gitlab                  ... 83.3% [#######################.....] [5 in 1m19.04268s]
panic: error: terraform apply for gitlab failed exit status 1

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000523bc0?, 0x0?})
	/go/pkg/mod/github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000367ec0, {0xc000523bc0, 0x36})
	/go/pkg/mod/github.com/rs/zerolog@v1.28.0/event.go:156 +0x2a5
github.com/rs/zerolog.(*Event).Msgf(0xc000367ec0, {0x1d39661?, 0x23?}, {0xc0004ed558?, 0x2?, 0x2?})
	/go/pkg/mod/github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/kubefirst/kubefirst/internal/gitlab.ApplyGitlabTerraform(0x0, {0x10?, 0x1cf8604?})
	/home/developer/app/internal/gitlab/gitlab.go:295 +0x4cd
github.com/kubefirst/kubefirst/cmd.glob..func13(0xc0000bfa00?, {0x2daab40, 0x0, 0x0})
	/home/developer/app/cmd/createGitlab.go:223 +0x1535
github.com/kubefirst/kubefirst/cmd.glob..func11(0x2d5c820?, {0x2daab40, 0x0, 0x0})
	/home/developer/app/cmd/create.go:131 +0x7a3
github.com/spf13/cobra.(*Command).execute(0x2d5c820, {0x2daab40, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2d5cd20)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:37 +0x25
main.main()
	/home/developer/app/main.go:68 +0x585
```

# Logs
```bash 
2022-12-26T15:48 INF internal/gitlab/gitlab.go:267 > Executing applyGitlabTerraform
2022-12-26T15:48 INF ../../../../app/pkg/shell.go:39 >  export AWS_SDK_LOAD_CONFIG = *
2022-12-26T15:48 INF ../../../../app/pkg/shell.go:39 >  export AWS_PROFILE = *******
2022-12-26T15:48 INF ../../../../app/pkg/shell.go:39 >  export GITLAB_TOKEN = ********************
2022-12-26T15:48 INF ../../../../app/pkg/shell.go:39 >  export GITLAB_BASE_URL = *********************
2022-12-26T15:48 INF ../../../../app/pkg/shell.go:39 >  export AWS_SDK_LOAD_CONFIG = *
2022-12-26T15:48 INF ../../../../app/pkg/shell.go:39 >  export AWS_PROFILE = *******
2022-12-26T15:48 INF ../../../../app/pkg/shell.go:39 >  export GITLAB_TOKEN = ********************
2022-12-26T15:48 INF ../../../../app/pkg/shell.go:39 >  export GITLAB_BASE_URL = *********************
2022-12-26T15:48 ERR ../../../../app/pkg/shell.go:77 > command "/home/developer/.k1/tools/terraform" failed error="exit status 1"
2022-12-26T15:48 PNC ../../../../app/internal/gitlab/gitlab.go:295 > error: terraform apply for gitlab failed exit status 1
2022-12-26T15:48 INF ../../../../app/cmd/create.go:41 > [000] Create duration is 3m0.514810303s

```

**Comment by 6za** [comment]
In info mode, it is a bit trick to troubleshoot cloud install.

**Comment by 6za** [comment]
```bash 
2022-12-26T15:55 INF github.com/kubefirst/kubefirst/cmd/createGitlab.go:202 > gitlab is ready!
2022-12-26T15:55 INF github.com/kubefirst/kubefirst/internal/k8s/kubernetes.go:239 > kubectl port-forward started for (svc/gitlab-webservice-default) available at http://localhost:8888
2022-12-26T15:55 INF github.com/kubefirst/kubefirst/internal/k8s/kubernetes.go:247 > /home/developer/.k1/tools/kubectl --kubeconfig /home/developer/.k1/gitops/terraform/base/kubeconfig -n gitlab port-forward svc/gitlab-webservice-default 8888:8080
2022-12-26T15:55 INF github.com/kubefirst/kubefirst/cmd/createUtils.go:311 > Gitlab available at http://localhost:8888
2022-12-26T15:55 INF github.com/kubefirst/kubefirst/cmd/createUtils.go:311 > Gitlab setup tokens
2022-12-26T15:55 INF github.com/kubefirst/kubefirst/internal/gitlab/gitlab.go:201 > discovering gitlab toolbox pod
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/internal/gitlab/gitlab.go:214 > discovering gitlab toolbox pod
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/internal/gitlab/gitlab.go:227 > gitlab initial root password secret name: gitlab-gitlab-initial-root-password
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/cmd/createUtils.go:311 > Gitlab terraform
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/internal/gitlab/gitlab.go:267 > Executing applyGitlabTerraform
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:35 > Debug: Running /home/developer/.k1/tools/terraform
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export AWS_SDK_LOAD_CONFIG = *
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export AWS_PROFILE = *******
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export GITLAB_TOKEN = ********************
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export GITLAB_BASE_URL = *********************
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: Initializing modules...
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT:
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: Initializing the backend...
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT:
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: Initializing provider plugins...
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: - Reusing previous version of gitlabhq/gitlab from the dependency lock file
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: - Reusing previous version of hashicorp/aws from the dependency lock file
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: - Using previously-installed gitlabhq/gitlab v15.7.1
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: - Using previously-installed hashicorp/aws v4.48.0
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT:
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: Terraform has been successfully initialized!
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT:
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: You may now begin working with Terraform. Try running "terraform plan" to see
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: any changes that are required for your infrastructure. All Terraform commands
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: should now work.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT:
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: If you ever set or change modules or backend configuration for Terraform,
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: rerun this command to reinitialize your working directory. If you forget, other
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: commands will detect it and remind you to do so if necessary.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:35 > Debug: Running /home/developer/.k1/tools/terraform
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export GITLAB_TOKEN = ********************
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export GITLAB_BASE_URL = *********************
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export AWS_SDK_LOAD_CONFIG = *
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export AWS_PROFILE = *******
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: Provider produced invalid plan
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ for gitlab_group.admins.require_two_factor_authentication: planned value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ cty.False for a non-computed attribute.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ own issue tracker.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: Provider produced invalid plan
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ for gitlab_group.admins.subgroup_creation_level: planned value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ cty.StringVal("owner") for a non-computed attribute.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ own issue tracker.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: Provider produced invalid plan
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ for gitlab_group.admins.two_factor_grace_period: planned value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ cty.NumberIntVal(48) for a non-computed attribute.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ own issue tracker.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: Provider produced invalid plan
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ for gitlab_group.admins.share_with_group_lock: planned value cty.False for
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ a non-computed attribute.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ own issue tracker.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: Provider produced invalid plan
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ for gitlab_group.admins.lfs_enabled: planned value cty.True for a
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ non-computed attribute.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ own issue tracker.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: Provider produced invalid plan
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ for gitlab_group.admins.mentions_disabled: planned value cty.False for a
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ non-computed attribute.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ own issue tracker.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: Provider produced invalid plan
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ for gitlab_group.admins.parent_id: planned value cty.NumberIntVal(0) for a
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ non-computed attribute.
2022-12-26T15:56 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-26T15:56 ERR github.com/kubefirst/kubefirst/pkg/shell.go:77 > command "/home/developer/.k1/tools/terraform" failed error="exit status 1"
2022-12-26T15:56 PNC github.com/kubefirst/kubefirst/internal/gitlab/gitlab.go:295 > error: terraform apply for gitlab failed exit status 1
2022-12-26T15:56 INF github.com/kubefirst/kubefirst/cmd/create.go:41 > [000] Create duration is 3m2.020592343s
```

**Comment by 6za** [comment]
I think this may be an issue on the Gitlab provider: 
https://gitlab.com/gitlab-org/terraform-provider-gitlab/-/issues

**Comment by 6za** [comment]
- Issue persists

```bash 
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export AWS_SDK_LOAD_CONFIG = *
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export AWS_PROFILE = *******
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export GITLAB_TOKEN = ********************
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export GITLAB_BASE_URL = *********************
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export AWS_SDK_LOAD_CONFIG = *
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export AWS_PROFILE = *******
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export GITLAB_TOKEN = ********************
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/pkg/shell.go:39 >  export GITLAB_BASE_URL = *********************
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╷
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Error: Provider produced invalid plan
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for gitlab_group.developers.auto_devops_enabled: planned value cty.False
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for a non-computed attribute.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ own issue tracker.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╵
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╷
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Error: Provider produced invalid plan
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for gitlab_group.developers.prevent_forking_outside_group: planned value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ cty.False for a non-computed attribute.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ own issue tracker.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╵
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╷
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Error: Provider produced invalid plan
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for gitlab_group.developers.share_with_group_lock: planned value cty.False
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for a non-computed attribute.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ own issue tracker.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╵
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╷
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Error: Provider produced invalid plan
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for gitlab_group.developers.emails_disabled: planned value cty.False for a
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ non-computed attribute.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ own issue tracker.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╵
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╷
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Error: Provider produced invalid plan
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for gitlab_group.developers.mentions_disabled: planned value cty.False for
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ a non-computed attribute.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ own issue tracker.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╵
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╷
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Error: Provider produced invalid plan
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for gitlab_group.developers.default_branch_protection: planned value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ cty.NumberIntVal(2) for a non-computed attribute.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ This is a bug in the provider, which should be reported in the provider's
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ own issue tracker.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╵
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: ╷
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Error: Provider produced invalid plan
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ Provider "registry.terraform.io/gitlabhq/gitlab" planned an invalid value
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for gitlab_group.developers.request_access_enabled: planned value cty.False
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │ for a non-computed attribute.
2022-12-28T13:07 WRN github.com/kubefirst/kubefirst/pkg/shell.go:72 > ERR: │
2022-12-28T13:07 ERR github.com/kubefirst/kubefirst/pkg/shell.go:79 > command "/home/developer/.k1/tools/terraform" failed error="exit status 1"
2022-12-28T13:07 PNC github.com/kubefirst/kubefirst/internal/gitlab/gitlab.go:295 > error: terraform apply for gitlab failed exit status 1
2022-12-28T13:07 INF github.com/kubefirst/kubefirst/cmd/create.go:41 > [000] Create duration is 24m9.588197588s
```

**Comment by pagottoo** [comment]
Breaking changes due to bumping version 3.20.0 to 15.7
https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/guides/version-15.7-upgrade

Fixing the provider version on 3.20.0 should resolve the issue.

**Comment by 6za** [comment]
Tested, It is working as expected now.
