### ISSUE TITLE
Github-aws -- Destroy fails to remove cluster(ELB not removed)

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1015]
# Output

```bash 
- successfully destroyed github resources
- Destroying Cluster
Destroy Cloud                 ... 75.0% [#####################.......] [3 in 31m27.201093s]
Open Ports                    ... 33.3% [#########...................] [1 in 31m27.201157s]
[####################################................................] [31m27s]
panic: failed to terraform destroy base

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0x1d2234a?, 0x0?})
	github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0003a8960, {0x1d2234a, 0x20})
	github.com/rs/zerolog@v1.28.0/event.go:156 +0x2a5
github.com/rs/zerolog.(*Event).Msg(...)
	github.com/rs/zerolog@v1.28.0/event.go:108
github.com/kubefirst/kubefirst/internal/terraform.DestroyBaseTerraform(0x0)
	github.com/kubefirst/kubefirst/internal/terraform/terraform.go:224 +0x58a
github.com/kubefirst/kubefirst/cmd.glob..func16(0x1cf70b4?, {0x1cf8079?, 0xc0004c8410?, 0xbb3040?})
	github.com/kubefirst/kubefirst/cmd/destroyAwsGithub.go:186 +0xd16
github.com/kubefirst/kubefirst/cmd.glob..func15(0x2d50d00?, {0x2da1aa0, 0x0, 0x0})
	github.com/kubefirst/kubefirst/cmd/destroy.go:29 +0x119
github.com/spf13/cobra.(*Command).execute(0x2d50d00, {0x2da1aa0, 0x0, 0x0})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2d53c80)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	github.com/kubefirst/kubefirst/cmd/root.go:37 +0x25
main.main()
	github.com/kubefirst/kubefirst/main.go:68 +0x585
```

# Logs

```bash 
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: module.eks.module.vpc.aws_subnet.public[0]: Still destroying... [id=subnet-0be21202e2d051a79, 20m0s elapsed]
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: ╷
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │ Warning: Version constraints inside provider configuration blocks are deprecated
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: deleting EC2 Subnet (subnet-0be21202e2d051a79): DependencyViolation: The subnet 'subnet-0be21202e2d051a79' has dependencies and cannot be deleted.
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ 	status code: 400, request id: 2f522866-cb5e-4ee8-b6a8-7c615d0b350b
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │   on eks/main.tf line 6, in provider "local":
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │    6:   version = "~> 2.1.0"
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │ Terraform 0.13 and earlier allowed provider version constraints inside the
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │ provider configuration block, but that is now deprecated and will be
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │ removed in a future version of Terraform. To silence this warning, move the
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │ provider version constraint into the required_providers block.
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: deleting EC2 Subnet (subnet-0e02344bc0e4b40f3): DependencyViolation: The subnet 'subnet-0e02344bc0e4b40f3' has dependencies and cannot be deleted.
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ 	status code: 400, request id: 40f9f79f-6fed-4c8f-b491-fe6a98a04cd9
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: │ (and one more similar warning elsewhere)
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:64 > OUT: ╵
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: error detaching EC2 Internet Gateway (igw-074e19dd6d963d147) from VPC (vpc-0a1156587bf1d76b0): DependencyViolation: Network vpc-0a1156587bf1d76b0 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ 	status code: 400, request id: e980e023-a253-4eea-ba1f-0d74267ea15b
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╷
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ Error: deleting EC2 Subnet (subnet-04032a1d204a08a23): DependencyViolation: The subnet 'subnet-04032a1d204a08a23' has dependencies and cannot be deleted.
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │ 	status code: 400, request id: 02e09cb8-4d33-4076-8ba9-589d17cfbf64
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: │
2022-12-27T19:08 DBG github.com/kubefirst/kubefirst/pkg/shell.go:70 > ERR: ╵
2022-12-27T19:08 ERR github.com/kubefirst/kubefirst/pkg/shell.go:77 > command "/home/developer/.k1/tools/terraform" failed error="exit status 1"
2022-12-27T19:08 PNC github.com/kubefirst/kubefirst/internal/terraform/terraform.go:224 > failed to terraform destroy base error="exit status 1"
2022-12-27T19:08 INF github.com/kubefirst/kubefirst/cmd/destroyAwsGithub.go:102 > Closed argocd port forward
```

# Workaround

- [X] Go to aws pannel and manually delete ELD and SG group for this ELB and run destroy again.

**Comment by 6za** [comment]
Solution:
- [ ] Check if the ELB listed on the `.kubefirst` file and remove it
- [ ] Check if the SG of the ELB listed on the `.kubefirst` file and remove it(wait a bit, to allow load balancer to be fully removed)

**Comment by 6za** [comment]
Changes applied and tested. It works as expected.
