### ISSUE TITLE
Github terraform failure on cluster create

### ISSUE THREAD

**Issue by dweebo** [kubefirst/kubefirst#1160]
I attempted to run the `kubefirst cluster create` command to create a new cluster, it failed with:

```
panic: error: terraform apply for github failed exit status 1

goroutine 1 [running]:
log.Panicf({0x294d6cb?, 0xc00010d540?}, {0xc0004d1570?, 0xc0004d1580?, 0x2?})
	/opt/hostedtoolcache/go/1.19.3/x64/src/log/log.go:395 +0x67
github.com/kubefirst/kubefirst/internal/github.ApplyGitHubTerraform(0x0)
	/home/runner/work/kubefirst/kubefirst/internal/github/github.go:47 +0x525
github.com/kubefirst/kubefirst/cmd.glob..func20(0x2930c62?, {0x1e?, 0x290333c?, 0x6?})
	/home/runner/work/kubefirst/kubefirst/cmd/githubAdd.go:41 +0x16f
github.com/kubefirst/kubefirst/cmd.glob..func12(0xc0001b4b60?, {0x39e25a0, 0x0, 0x0})
	/home/runner/work/kubefirst/kubefirst/cmd/createGithub.go:63 +0x22e
github.com/kubefirst/kubefirst/cmd.glob..func11(0x39948a0?, {0x39e25a0, 0x0, 0x0})
	/home/runner/work/kubefirst/kubefirst/cmd/create.go:144 +0x862
github.com/spf13/cobra.(*Command).execute(0x39948a0, {0x39e25a0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x3994b20)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/runner/work/kubefirst/kubefirst/cmd/root.go:37 +0x25
main.main()
	/home/runner/work/kubefirst/kubefirst/main.go:65 +0x41d
```
Looking at the logs I see this error message
```
LOG: 2023/01/15 12:41:32.423782 /home/runner/work/kubefirst/kubefirst/pkg/shell.go:64: OUT:  github_user_ssh_key.kubefirst_bot: Creation complete after 4s [id=76397434]
LOG: 2023/01/15 12:41:32.859761 /home/runner/work/kubefirst/kubefirst/pkg/shell.go:70: ERR:  ╷
LOG: 2023/01/15 12:41:32.859845 /home/runner/work/kubefirst/kubefirst/pkg/shell.go:70: ERR:  │ Error: POST https://api.github.com/orgs/teamdweebo/teams: 403 Although you appear to have the correct authorization credentials, the `teamdweebo` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/ []
LOG: 2023/01/15 12:41:32.859909 /home/runner/work/kubefirst/kubefirst/pkg/shell.go:70: ERR:  │ 
LOG: 2023/01/15 12:41:32.859933 /home/runner/work/kubefirst/kubefirst/pkg/shell.go:70: ERR:  │   with github_team.admins,
LOG: 2023/01/15 12:41:32.859948 /home/runner/work/kubefirst/kubefirst/pkg/shell.go:70: ERR:  │   on teams.tf line 1, in resource "github_team" "admins":
LOG: 2023/01/15 12:41:32.859968 /home/runner/work/kubefirst/kubefirst/pkg/shell.go:70: ERR:  │    1: resource "github_team" "admins" {
LOG: 2023/01/15 12:41:32.859986 /home/runner/work/kubefirst/kubefirst/pkg/shell.go:70: ERR:  │ 
```

After following the steps in https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/disabling-oauth-app-access-restrictions-for-your-organization I was able to successfully get past this issue.

Ideally kubefirst could work even if these OAuth app access restrictions are enabled, or at least detect this setting and explain it to the user.

**Comment by dweebo** [comment]
Maybe it would have worked if I followed the directions on https://docs.kubefirst.io/kubefirst/github/install.html in "Step 2 - Create your kubefirst bot user and a personal access token"

**Comment by converge** [comment]
@dweebo do you have something similar to this in your organization setup (k1-dev1-org1 is my testing organization) ?

![Screenshot 2023-01-16 at 08 57 46](https://user-images.githubusercontent.com/188671/212673188-4502d274-d7a4-4b42-9475-0a006add1a93.png)

Did you issue the token using the purple GitHub login page that uses the GitHub device flow (that one that opens the browser and ask for a 6-digit code) ? If yes, did you gave permission to your orgnanization after providing the code, in the GitHub page?

**Comment by fharper** [comment]
@dweebo do you still have issue with your kubefirst deployment?

**Comment by echoboomer** [comment]
Closing due to inactivity. Note that in release v2 which releases shortly, this logic has been rewritten. Please let us know if similar issues are seen in the future.
