### ISSUE TITLE
Error refreshing state: NotFound: Not Found

### ISSUE THREAD

**Issue by jizusun** [kubefirst/kubefirst#1378]
### Which version of kubefirst are you using?

1.11.1

### Which installation type?

k3d (local)

### Which distributed Git provider?

GitHub

### What is the issue?

I tried for several times, but all failed with 
```
2023-03-20T15:03 WRN kubefirst/pkg/ExecShellWithVars/shell.go:77 > ERR: Error refreshing state: NotFound: Not Found
2023-03-20T15:03 WRN kubefirst/pkg/ExecShellWithVars/shell.go:77 > ERR:         status code: 404, request id: , host id:
2023-03-20T15:03 ERR pkg/shell.go:84 > command "/home/jizu/.k1/tools/terraform" failed error="exit status 1"
2023-03-20T15:03 PNC internal/terraform/terraform.go:373 > error: terraform init for /home/jizu/.k1/gitops/terraform/vault failed exit status 1
```

Detailed logs

```sh
➜  kubefirst git:(main) ✗ kubefirst local

-----------
Follow your logs with:
   tail -f  /home/jizu/Code/k3d-argocd/kubefirst/logs/log_1679295128.log

-----------
- Sending installation telemetry
Download dependencies         ... done! [3 in 2m11.918s]
Create SSH keys               ... done! [1 in 2m11.923s]
Clone and Detokenize (GitOps) ... done! [1 in 2m14.263s]
- initialization step is done!
Process Parameters            ... done! [1 in 2m16.656s]
- Creating github resources with terraform
- Created gitops Repo in github.com/jizusun
- pushing local detokenized gitops content to new remote github.com/jizusun
Setup gitops on github        ... done! [3 in 1m40.517s]
- create initial argocd repository
- helm repo add argo https://argoproj.github.io/argo-helm and helm repo update
- helm install argo and wait
- ArgoCD is running, continuing
- Setting argocd username and password credentials
- argocd username and password credentials set successfully
- Getting an argocd auth token
- argocd admin auth token set
- applying the registry application to argocd
- waiting for Vault to be ready...
- configuring vault with terraform
Setup base cluster            ... 50.0% [##############..............] [1 in 8m48.143911s]
Install apps to cluster       ... 50.0% [##############..............] [2 in 8m48.143926s]
panic: error: terraform init for /home/jizu/.k1/gitops/terraform/vault failed exit status 1

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000d1a0c0?, 0x0?})
        github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc00051e120, {0xc000d1a0c0, 0x54})
        github.com/rs/zerolog@v1.28.0/event.go:156 +0x2a5
github.com/rs/zerolog.(*Event).Msgf(0xc00051e120, {0x1d57fb9?, 0x1e?}, {0xc0009a77a0?, 0x1?, 0x1?})
        github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/kubefirst/kubefirst/internal/terraform.initActionAutoApprove(0x0, {0x1d15762, 0x5}, {0xc000799e90, 0x25})
        github.com/kubefirst/kubefirst/internal/terraform/terraform.go:373 +0x52d
github.com/kubefirst/kubefirst/internal/terraform.InitApplyAutoApprove(...)
        github.com/kubefirst/kubefirst/internal/terraform/terraform.go:475
github.com/kubefirst/kubefirst/cmd/local.runLocal(0xc000146c80?, {0x1d149ca?, 0x0?, 0x0?})
        github.com/kubefirst/kubefirst/cmd/local/local.go:311 +0x1066
github.com/spf13/cobra.(*Command).execute(0xc000146c80, {0x2dfc288, 0x0, 0x0})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2dae2c0)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
        github.com/kubefirst/kubefirst/cmd/root.go:37 +0x25
main.main()
        github.com/kubefirst/kubefirst/main.go:73 +0x5ea
```

The log

```sh
2023-03-20T15:03 INF internal/k8s/kubernetes.go:427 > vault is not ready yet, sleeping and checking again, attempt (8/50)
2023-03-20T15:03 INF internal/k8s/kubernetes.go:465 > vault is initialized and is in the expected state
2023-03-20T15:03 INF pkg/helpers.go:627 > configuring vault with terraform
2023-03-20T15:03 INF internal/terraform/terraform.go:46 > Collecting Vault Vars
2023-03-20T15:03 INF pkg/shell.go:44 >  export TF_VAR_email_address =
2023-03-20T15:03 INF pkg/shell.go:44 >  export TF_VAR_github_token = ****************************************
2023-03-20T15:03 INF pkg/shell.go:44 >  export TF_VAR_vault_addr = *************************
2023-03-20T15:03 INF pkg/shell.go:44 >  export VAULT_ADDR = *************************
2023-03-20T15:03 INF pkg/shell.go:44 >  export VAULT_TOKEN = ********************
2023-03-20T15:03 INF pkg/shell.go:44 >  export TF_VAR_atlantis_repo_webhook_url = ***********************************************
2023-03-20T15:03 INF pkg/shell.go:44 >  export TF_VAR_vault_token = ********************
2023-03-20T15:03 INF pkg/shell.go:44 >  export TF_VAR_atlantis_repo_webhook_secret = ********************
2023-03-20T15:03 INF pkg/shell.go:44 >  export TF_VAR_kubefirst_bot_ssh_public_key = *********************************************************************************
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT: Initializing modules...
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT: - argo in modules/oidc-client
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT: - argocd in modules/oidc-client
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT: - console in modules/oidc-client
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT: - gitlab in modules/oidc-client
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT:
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT: Initializing the backend...
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT:
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT: Successfully configured the backend "s3"! Terraform will automatically
2023-03-20T15:03 INF kubefirst/pkg/ExecShellWithVars/shell.go:69 > OUT: use this backend unless the backend configuration changes.
2023-03-20T15:03 WRN kubefirst/pkg/ExecShellWithVars/shell.go:77 > ERR: Error refreshing state: NotFound: Not Found
2023-03-20T15:03 WRN kubefirst/pkg/ExecShellWithVars/shell.go:77 > ERR:         status code: 404, request id: , host id:
2023-03-20T15:03 ERR pkg/shell.go:84 > command "/home/jizu/.k1/tools/terraform" failed error="exit status 1"
2023-03-20T15:03 PNC internal/terraform/terraform.go:373 > error: terraform init for /home/jizu/.k1/gitops/terraform/vault failed exit status 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Since I got no reply, I will assume it's not a problem anymore. If my assumption is wrong, please reopen the issue or create a new one.
