### ISSUE TITLE
kubefirst reset should be tolerant of missing .k1 / .kubefirst

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1484]
**What would you like to be added**:
edge case circumstance, but would like to be able to run `kubefirst reset` on a new host without error even if .k1 / .kubefirst doesn't exist yet.

**Why is this needed**:
```
➜  ~ rm -rf ~/.kubefirst
➜  ~ rm -rf ~/.k1       
➜  ~ kubefirst reset      
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/kubefirst/kubefirst/cmd.parseConfigEntryKubefirstChecks({0x0?, 0x0?})
	github.com/kubefirst/kubefirst/cmd/reset.go:73 +0x280
github.com/kubefirst/kubefirst/cmd.glob..func3(0x108901fa0?, {0x10688a56e?, 0x0?, 0x0?})
	github.com/kubefirst/kubefirst/cmd/reset.go:42 +0x124
github.com/spf13/cobra.(*Command).execute(0x108901fa0, {0x108962e38, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x108902280)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kubefirst/kubefirst/cmd.Execute()
	github.com/kubefirst/kubefirst/cmd/root.go:46 +0x2c
main.main()
	github.com/kubefirst/kubefirst/main.go:87 +0x590
```

**Comment by echoboomer** [comment]
https://github.com/kubefirst/kubefirst/pull/1505
