### ISSUE TITLE
Check if a console for installation is already up

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1597]
### Which version of kubefirst are you using?

v2.1

### Which installation type?

None specific

### Which distributed Git provider?

None specific

### What is the issue?

If you try to `kubefirst launch up` and there's already a k3d console cluster, there will be an error

```
stat /Users/fharper/.k1/kubefirst-console/kubeconfig: no such file or directory
ERRO[0004] unable to locate kubeconfig file - checked path: /Users/fharper/.k1/kubefirst-console/kubeconfig
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1022f7490]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x140000f8000?)
	k8s.io/client-go@v11.0.1-0.20190816222228-6d55c1b1f1ca+incompatible/kubernetes/clientset.go:414 +0x20
github.com/kubefirst/runtime/pkg/k8s.CreateKubeConfig(0x90?, {0x14000976000?, 0x14000d1f8e8?})
	github.com/kubefirst/runtime@v0.1.46/pkg/k8s/client.go:73 +0x268
github.com/kubefirst/kubefirst/cmd.launchUp.func1(0x14000773800?, {0x102b78570?, 0x0?, 0x0?})
	github.com/kubefirst/kubefirst/cmd/launch.go:233 +0x1050
github.com/spf13/cobra.(*Command).execute(0x14000773800, {0x104cf8808, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x104c97520)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kubefirst/kubefirst/cmd.Execute()
	github.com/kubefirst/kubefirst/cmd/root.go:48 +0x30
main.main()
	github.com/kubefirst/kubefirst/main.go:87 +0x590
```

As a precheck, we need to check if it already exist before trying to create another one.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
Fixed by release `v2.1.6`.
