### ISSUE TITLE
k3d doesn't work on macbook M1

### ISSUE THREAD

**Issue by Noksa** [kubefirst/kubefirst#1674]
### Which version of kubefirst are you using?

kubefirst-cli golang utility version: v2.2.2

### Which cloud provider?

k3d (local)

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### What is the issue?

```
❯ kubefirst kubefirst k3d create
------------------------------------------------
Follow your logs in a new terminal with:
   tail -f -n +1 /Users/alexandr/.k1/logs/log_1688552421.log
------------------------------------------------
Running preflight checks                ... done! [5 in 33ms]
Cloning and formatting git repositories ...  0.0% [......................................] [0 in 3.668253s]
[###########################################.............................................] [4s]
Error: repository already exists

If a detailed error message was available, please make the necessary corrections before retrying.
You can re-run the last command to try the operation again.
```

```
❯ gitops (main) ✘ echo $(pwd)
/Users/alexandr/.k1/kubefirst/gitops
❯ gitops (main) ✘ git remote -v
github	https://github.com/Noksa/gitops.git (fetch)
github	https://github.com/Noksa/gitops.git (push)
origin	https://github.com/kubefirst/gitops-template.git (fetch)
origin	https://github.com/kubefirst/gitops-template.git (push)
```

Logs:
```
2023-07-05T13:20 INF cmd/k3d/create.go:213 > verifying github authentication
2023-07-05T13:20 INF runtime/pkg/handlers/GitHubHandler/github.go:173 > GitHub user: Noksa
2023-07-05T13:20 INF cmd/k3d/create.go:376 > kubefirst version configs.K1Version: v2.2.2
2023-07-05T13:20 INF cmd/k3d/create.go:377 > cloning gitops-template repo url: https://github.com/kubefirst/gitops-template.git
2023-07-05T13:20 INF cmd/k3d/create.go:378 > cloning gitops-template repo branch: v2.2.2
2023-07-05T13:20 INF cmd/k3d/create.go:387 > checking authentication to required providers
2023-07-05T13:20 INF cmd/k3d/create.go:440 > already completed github checks - continuing
2023-07-05T13:20 INF cmd/k3d/create.go:465 > already setup kbot user - continuing
2023-07-05T13:20 INF cmd/k3d/create.go:469 > validation and kubefirst cli environment check is complete
2023-07-05T13:20 INF cmd/k3d/create.go:540 > already completed download of dependencies to `$HOME/.k1/tools` - continuing
2023-07-05T13:20 INF cmd/k3d/create.go:560 > generating your new gitops repository
2023-07-05T13:20 INF pkg/gitClient/git.go:49 > cloning url: https://github.com/kubefirst/gitops-template.git - git ref: v2.2.2
2023-07-05T13:20 INF pkg/k3d/create.go:127 > gitops repository clone complete
2023-07-05T13:20 INF pkg/gitClient/git.go:96 > git remote add github https://github.com/Noksa/gitops.git
```

Okay... let's remove it and recreate and we get panic:
```
❯ gitops (main) ✘ kubefirst k3d destroy
------------------------------------------------
Follow your logs in a new terminal with:
   tail -f -n +1 /Users/alexandr/.k1/logs/log_1688552477.log
------------------------------------------------
stat /Users/alexandr/.k1/kubefirst/kubeconfig: no such file or directory
ERRO[0000] unable to locate kubeconfig file - checked path: /Users/alexandr/.k1/kubefirst/kubeconfig
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105d846e0]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x14000192000?)
	k8s.io/client-go@v11.0.1-0.20190816222228-6d55c1b1f1ca+incompatible/kubernetes/clientset.go:414 +0x20
github.com/kubefirst/runtime/pkg/k8s.CreateKubeConfig(0x60?, {0x140004c1c20?, 0x2c?})
	github.com/kubefirst/runtime@v0.1.75/pkg/k8s/client.go:73 +0x268
github.com/kubefirst/kubefirst/cmd/k3d.destroyK3d(0x14000ed0f00?, {0x106af5411?, 0x0?, 0x0?})
	github.com/kubefirst/kubefirst/cmd/k3d/destroy.go:78 +0x414
github.com/spf13/cobra.(*Command).execute(0x14000ed0f00, {0x10964f530, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1095e0dc0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/kubefirst/kubefirst/cmd.Execute()
	github.com/kubefirst/kubefirst/cmd/root.go:48 +0x30
main.main()
	github.com/kubefirst/kubefirst/main.go:87 +0x590
```

Let's remove `gitops` folder manually and repeat:
```
❯ gitops (main) ✘ rm -rf ~/.k1/kubefirst/gitops
❯ gitops kubefirst k3d create
------------------------------------------------
Follow your logs in a new terminal with:
   tail -f -n +1 /Users/alexandr/.k1/logs/log_1688552543.log
------------------------------------------------
Running preflight checks                ... done! [5 in 33ms]
Cloning and formatting git repositories ...  0.0% [......................................] [0 in 2.868589s]
[###########################################.............................................] [3s]
Error: repository already exists

If a detailed error message was available, please make the necessary corrections before retrying.
You can re-run the last command to try the operation again.
```

Same result.

Does it work on arm macbooks?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
Do you already have a repository called `gitops` in your GitHub account by any chance? The panic during `destroy` comes from a dependency on the `kubeconfig` file in the `~/.k1/kubefirst` folder, so if that had been deleted at that point, it wouldn't work - you'd also get the same error if you tried to run `destroy` and nothing had technically been created yet, although we do use a file at `~/.kubefirst` to keep track of that. Any chance you can provide the content of that file with your sensitive information stripped?

**Comment by fharper** [comment]
So as mentioned by @echoboomer, the error you have on `kubefirst k3d create` is normal since you already have a repository named `gitops`.

Seems like you forked the `gitops_template` repository on your account, and want to it to be the `gitops-template` repository kubefirst will use to create your cluster.

If you want to use your forked repository, you need to add the flag `--gitops-template-url` with the URL to your own repository. The problem will persist though, because you named it `gitops` and not another name, so I would suggest you rename it to something else, like `gitops-template` as kubefirst will need to create a repository named `gitops`.

Worth mentioning that the `gitops` repository created is a subset of `gitops-template` as the template contains all files, and configurations for all combinations of clouds + git providers: the end result, the `gitops` repository, will contain only the files needed for k3d + GitHub, which is your choice right now.

**Comment by Noksa** [comment]
@echoboomer @fharper I don't have a repository with name `gitops` or `gitops_template`

**Comment by fharper** [comment]
Oh, my bad, I saw the `git remote` command, but didn't realize you were in the `.k1` repository.

I just ran k3d on my laptop right now: I'm on M1, and I had no issue. If you run `kubefirst k3d reset` and try to run `kubefirst k3d create` again, do you have the same error?

**Comment by Noksa** [comment]
@fharper 
There is no such command
```
❯ ~ kubefirst version

kubefirst-cli golang utility version: v2.2.2
```

```
❯ ~ kubefirst k3d reset
kubefirst k3d

Usage:
  kubefirst k3d [command]

Available Commands:
  create           create the kubefirst platform running in k3d on your localhost
  destroy          destroy the kubefirst platform
  mkcert           create a single ssl certificate for a local application
  root-credentials retrieve root authentication information for platform components
  unseal-vault     check to see if an existing vault instance is sealed and, if so, unseal it

Flags:
  -h, --help   help for k3d

Use "kubefirst k3d [command] --help" for more information about a command.
```

**Comment by fharper** [comment]
Sorry, my bad, it's `kubefirst reset`.

**Comment by fharper** [comment]
@Noksa: if you want, we can try to debug this live on our [Slack Community](https://kubefirst.io/slack).

**Comment by Claywd** [comment]
@Noksa How are things working for you now?

**Comment by fharper** [comment]
@Noksa we'll assume this issue is close since we didn't hear from you in the last three weeks. If it's still a problem, please create a new issue, or ask in the #helping-hands channel in our [Slack Community](https://kubefirst.io/slack).
