### ISSUE TITLE
Fail gracefully if region is down

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1686]
### Which version of kubefirst are you using?

v.2.2.2

### Which cloud provider?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

None specific

### What is the issue?

If one of the cloud region is down (currently experiencing it with Civo & NYC1), the CLI will display this error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102816860]

goroutine 1 [running]:
github.com/kubefirst/runtime/pkg/civo.(*CivoConfiguration).createAccessCredentials(0x14000ebeac8, {0x14000ac4d80, 0x24}, {0x102df4e75, 0x4})
	github.com/kubefirst/runtime@v0.1.75/pkg/civo/objectStorage.go:129 +0x120
github.com/kubefirst/runtime/pkg/civo.(*CivoConfiguration).GetAccessCredentials(0x14000ebeac8, {0x14000ac4d80, 0x24}, {0x102df4e75, 0x4})
	github.com/kubefirst/runtime@v0.1.75/pkg/civo/objectStorage.go:67 +0x1dc
github.com/kubefirst/kubefirst/cmd/civo.createCivo(0x1400060fb00?, {0x102df5411?, 0x8?, 0x8?})
	github.com/kubefirst/kubefirst/cmd/civo/create.go:402 +0x1fac
github.com/spf13/cobra.(*Command).execute(0x1400060fb00, {0x14000116300, 0x8, 0x8})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1058e0dc0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/kubefirst/kubefirst/cmd.Execute()
	github.com/kubefirst/kubefirst/cmd/root.go:48 +0x30
main.main()
	github.com/kubefirst/kubefirst/main.go:87 +0x590
```

When in reality, the region is down, and unreachable or 404 as shown in the logs

```
2023-07-12T13:40 INF runtime/pkg/civo/(*CivoConfiguration)/objectStorage.go:101 > looking for credential: k1-state-store-kubefirst-fred-2obfo1
2023-07-12T13:40 INF runtime/pkg/civo/(*CivoConfiguration)/objectStorage.go:104 > Error: Unknown error response - status: 404 Not Found, code: 404, reason: {"code":"database_region_not_found","reason":"Failed to find the region within the internal database"}

2023-07-12T13:40 INF runtime/pkg/civo/(*CivoConfiguration)/objectStorage.go:62 > Error: Unknown error response - status: 404 Not Found, code: 404, reason: {"code":"database_region_not_found","reason":"Failed to find the region within the internal database"}

2023-07-12T13:40 INF runtime/pkg/civo/(*CivoConfiguration)/objectStorage.go:66 > credential name: k1-state-store-kubefirst-fred-2obfo1 not found, creating
2023-07-12T13:40 INF runtime/pkg/civo/(*CivoConfiguration)/objectStorage.go:127 > Error: Unknown error response - status: 404 Not Found, code: 404, reason: {"code":"database_region_not_found","reason":"Failed to find the region within the internal database"}
```

The CLI should fail gracefully with a message mentioning the region is down at the moment, and let them know they should use the `--cloud-region` flag to choose another than the default one.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
It shouldn't be an issue anymore as the revamp of the CLI will use the API instead of its own code.

If the problem persist with v2.3+, please add a comment or create a new issue.
