### ISSUE TITLE
Google Cloud not working anymore

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1729]
### Which version of kubefirst are you using?

2.2.3+

### Which cloud provider?

Google Cloud

### Which installation type?

CLI

### Which distributed Git provider?

GitHub, GitLab

### What is the issue?

Since 2.2.3, you cannot create a cluster with Google Cloud. It was working with 2.2.2 (just tried it again by checking out `f58d9caa1049e23356efe6779de44a6ceb0d7d35`, which is the latest commit in 2.2.2, and using `go run`), so not sure what caused the issue. Here's the error now

```
panic: error opening repo at: /Users/fharper/.k1/kubefirst-fred/gitops, err: couldn't find remote ref "refs/heads/heads/"

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0x14001326000?, 0x0?})
	github.com/rs/zerolog@v1.29.0/log.go:376 +0x30
github.com/rs/zerolog.(*Event).msg(0x1400055a120, {0x14001326000, 0x72})
	github.com/rs/zerolog@v1.29.0/event.go:156 +0x278
github.com/rs/zerolog.(*Event).Msgf(0x1400055a120, {0x1048a3071?, 0x140002ae960?}, {0x14001823cf8?, 0x1048da488?, 0x30?})
	github.com/rs/zerolog@v1.29.0/event.go:129 +0x50
github.com/kubefirst/runtime/pkg/providerConfigs.PrepareGitRepositories({0x1048490a5, 0x3}, {0x16d6c2aa9, 0x6}, {0x16d6c2afa, 0xe}, {0x104849f6f, 0x4}, {0x140001481e0, 0x2b}, ...)
	github.com/kubefirst/runtime@v0.2.11/pkg/providerConfigs/adjustDriver.go:219 +0xf4
github.com/kubefirst/kubefirst/cmd/gcp.createGCP(0x14000570000?, {0x104849e2f?, 0xc?, 0xc?})
	github.com/kubefirst/kubefirst/cmd/gcp/create.go:674 +0x3a60
github.com/spf13/cobra.(*Command).execute(0x14000570000, {0x14000dd0cc0, 0xc, 0xc})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x10732d0a0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/kubefirst/kubefirst/cmd.Execute()
	github.com/kubefirst/kubefirst/cmd/root.go:48 +0x30
main.main()
	github.com/kubefirst/kubefirst/main.go:87 +0x590
```

I tried with the CLI, but I assume you'll get the same issue with the UI installation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Fixed in v2.2.6
