### ISSUE TITLE
[Feature] Add good error messages for port-forward errors

### ISSUE THREAD

**Issue by ShankyJS** [kubefirst/kubefirst#1740]
Hey! ✋🏻 

I was trying to use the brand new GCP Kubefirst when having an open port forward on port 8080, 

I received the following error;

````
kubefirst beta gcp create \
  --alerts-email my-mail \
  --github-org shankyjs-playground \
  --domain-name kubefirst.shankyjs.com \
  --dns-provider cloudflare --gcp-project test-gitops-kubefirst --cluster-name kubefirst --gitops-template-branch main
------------------------------------------------
Follow your logs in a new terminal with:
   tail -f -n +1 /Users/shankyjs/.k1/logs/log_1690868093.log
------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x10392c99c]

goroutine 1 [running]:
github.com/kubefirst/runtime/pkg/k8s.CheckForExistingPortForwards({0x14000c7e088, 0x3, 0x0?})
	github.com/kubefirst/runtime@v0.3.0/pkg/k8s/helpers.go:19 +0xac
github.com/kubefirst/kubefirst/cmd/gcp.createGCP(0x1400046cc00?, {0x1042c9c4f?, 0xe?, 0xe?})
	github.com/kubefirst/kubefirst/cmd/gcp/create.go:151 +0x4b4
github.com/spf13/cobra.(*Command).execute(0x1400046cc00, {0x14000668700, 0xe, 0xe})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x106dad0a0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/kubefirst/kubefirst/cmd.Execute()
	github.com/kubefirst/kubefirst/cmd/root.go:48 +0x30
main.main()
	github.com/kubefirst/kubefirst/main.go:87 +0x590
````

The feature would be adding an error handler for k8s.CheckForExistingPortForwards so it can display a beautiful message when the user has a port-forward open.

**Comment by fharper** [comment]
Firstly, thanks for reporting this issue @ShankyJS!

As discussed on our Slack community, you are willing to contribute and fix it yourself, so I assigned it to you. Thanks a lot!

If there's anything to discuss about this specific problem or how to tackle it, please let's do it here so there's public trace of what was discussed about the fix. If it's about how to contribute, or kubefirst code in general, feel free to discuss in the `#contributors` channel in the [Slack community](https://kubefirst.io/slack). We have [CONTRIBUTING.md](https://github.com/kubefirst/kubefirst/blob/main/CONTRIBUTING.md), but it's not as complete as we would like right now...

**Comment by ShankyJS** [comment]
Thanks! Will take a look tonight or tomorrow morning!

**Comment by fharper** [comment]
@ShankyJS I would not work on this for now. We'll need to review this issue with v2.3 as we are revamping the CLI to use our API instead of its own logic (easier to maintain), so it may not be an issue anymore.
