### ISSUE TITLE
panic: interface conversion: runtime.Object is *v1.Status, not *v1.StatefulSet

### ISSUE THREAD

**Issue by agardnerIT** [kubefirst/kubefirst#1908]
### Which version of kubefirst are you using?

v2.3.5

### Which cloud provider?

k3d (local)

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### Which Operating System?

macOS

### What is the issue?

Trying to install k3d variant on localhost (MacBook Air m1).

I've had some timeouts so keep executing `kubefirst k3d create` and it seems to pick up where it left off.

But now it panicked:

```
Running preflight checks                ... done! [5 in 1ms]
Cloning and formatting git repositories ... done! [1 in 0s]
Applying github Terraform               ... done! [1 in 0s]
Pushing git repositories                ... done! [1 in 0s]
Creating k3d cluster                    ... done! [1 in 0s]
Bootstrapping Kubernetes resources      ... done! [2 in 114ms]
Verifying Kubernetes cluster is ready   ... done! [3 in 24.072s]
Installing and configuring Argo CD      ...  0.0% [......................................] [0 in 56.507756s]
Installing and configuring Argo CD      ...  0.0% [......................................] [0 in 57.507833s]
Installing and configuring Argo CD      ...  0.0% [......................................] [0 in 1m3.907738s]
Installing and configuring Argo CD      ...  0.0% [......................................] [0 in 1m4.007746s]
Installing and configuring Argo CD      ...  0.0% [......................................] [0 in 1m26.607746s]
[#############################################################################...........] [1m51s]
Installing and configuring Argo CD      ... 33.3% [############..........................] [1 in 4m21.407335s]
[################################################################################........] [4m46s]
panic: interface conversion: runtime.Object is *v1.Status, not *v1.StatefulSet

goroutine 12 [running]:
github.com/kubefirst/runtime/pkg/k8s.WaitForStatefulSetReady(0x14000dda180, 0x14001849500, 0x12c, 0x0)
	github.com/kubefirst/runtime@v0.3.28/pkg/k8s/exec.go:453 +0x580
github.com/kubefirst/runtime/pkg/k8s.VerifyArgoCDReadiness(0x14000de46e0?, 0x1, 0x1029c444c?)
	github.com/kubefirst/runtime@v0.3.28/pkg/k8s/argocd.go:32 +0xb0
github.com/kubefirst/kubefirst/cmd/k3d.runK3d(0x140008f3500?, {0x1063a4e80?, 0x0?, 0x0?})
	github.com/kubefirst/kubefirst/cmd/k3d/create.go:946 +0x4fc8
github.com/spf13/cobra.(*Command).execute(0x140008f3500, {0x1063a4e80, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x10631c520)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/kubefirst/kubefirst/cmd.Execute()
	github.com/kubefirst/kubefirst/cmd/root.go:48 +0x2c
main.main.func2()
	github.com/kubefirst/kubefirst/main.go:91 +0x1c
created by main.main in goroutine 1
	github.com/kubefirst/kubefirst/main.go:90 +0x614
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Thanks for reporting this issue @agardnerIT. I was not able to reproduce the timeout, so not able to reproduce the second issue also.

What happen if you run `kubefirst k3d destroy` and try to create the cluster again?

If you get a timeout again, before running the command again, can you copy the logs, and shared them here.
