### ISSUE TITLE
An unfriendly error occurs when the hosted zone does not exist on Route53

### ISSUE THREAD

**Issue by hamc** [kubefirst/kubefirst#225]
## Description

During local setup initialization, an unfriendly error occurs when the host zone on Route53 does not exist.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc1942d]

goroutine 1 [running]:
github.com/kubefirst/kubefirst/internal/aws.TestHostedZoneLiveness(0xa0?, {0x7ffdb1637dd3, 0x9}, {0x0, 0x0})
        /Users/jdietz/git/github/kubefirst/kubefirst/internal/aws/aws.go:172 +0x7cd
github.com/kubefirst/kubefirst/cmd.glob..func9(0x2daaca0?, {0xc0001b7c20, 0x0, 0xa})
        /Users/jdietz/git/github/kubefirst/kubefirst/cmd/init.go:196 +0x1b7c
github.com/spf13/cobra.(*Command).execute(0x2daaca0, {0xc0001b79a0, 0xa, 0xa})
        /Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x2da9b20)
        /Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
        /Users/jdietz/git/github/kubefirst/kubefirst/cmd/root.go:26 +0x25
main.main()
        /Users/jdietz/git/github/kubefirst/kubefirst/main.go:65 +0x41d
```

No additional information is sent in the log.

## How to simulate:

Execute the init command using a AWS account without the hosted zone specified in option `--hosted-zone-name`. Eg:

`kubefirst init --admin-email myemail@email.com --cloud aws --hosted-zone-name nonexistentdomain.com --region us-east-1 --profile default`

**Comment by johndietz** [comment]
Thanks so much for the report @hamc. 

@kubefirst/engineers I've reproduced this issue on the latest codebase - fix needs to be included in our next release please. Thanks crew.
