### ISSUE TITLE
How to recover application configuration data if cluster goes down

### ISSUE THREAD

**Issue by Shivaraj600** [kubefirst/kubefirst#324]
Hi I have successfully created kubefirst cluster 

and i want to check my configuration towords application is saved or not

for example 

1.I created cluster and  logged in to my gitlab server url with given credentials  and created few test users

2.Then i destroy the cluster successfully  with command "kubefirst destroy"

Now i want to verify that if i create cluster again should i get same user which i created earlier ? for this

3. Again i fired command "kubefirst cluster create" to verify the same 
   but i am not able to create cluster again and getting following error
   
   Process Parameters            ... done! [1 in 1.003s]
- Creating K8S Cluster
Prepare Temporary Repo        ... 25.0% [#######.....................] [1 in 2.095905s]
Prepare Temporary Repo        ... 50.0% [##############..............] [2 in 2.995549s]
Bucket not found, missing SSL backup, assuming first installation, error is: couldn't list bucket contentspanic: stat /home/developer/.k1/gitops/terraform/base/kubeconfig: no such file or directory

goroutine 1 [running]:
github.com/kubefirst/kubefirst/cmd.glob..func6(0x2e04de0?, {0x2e528d0, 0x0, 0x0})
        /github/workspace/cmd/create.go:85 +0x3565
github.com/spf13/cobra.(*Command).execute(0x2e04de0, {0x2e528d0, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x2e05060)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
        /github/workspace/cmd/root.go:26 +0x25
main.main()
        /github/workspace/main.go:65 +0x41d

a. Please suggest how to recover my configuration if my cluster is goes down 

thank you in advance

**Comment by 6za** [comment]
If you want cycle/loop.. to create and destroy a cluster. The general idea is: 
- what `./kubefirst init` creates, like the buckets, `./kubefirst clean ` undo. 
- what `./kubefirst cluster create, then `./kubefirst destroy `undo it. 

So, if you want cycle.. `clean` has a flag to remove the buckets you just created.

**Comment by 6za** [comment]
If you didn't removed your buckets yet, we have a backup of of ~/.kubefirst at bucket called: `k1-state-store-*` on its root called `.kubefirst`. 

This bucket name suffix is random string or a string you passed to the int. 

Thank for the question, I hope this helps.

**Comment by 6za** [comment]
The issue you faced on your second create, is because you didn't run a clean, before creating again. That will have the previous install files and by-design fails. We are still improving a bit our error outputs to be more clear.

**Comment by 6za** [comment]
On your question 1, we need to double-check, In theory if you recreate the idea is that you have all blank as the first-time. 

The only scenario I see some "recycling" of previous state like users if you share the same buckets of state from a previous install, but that is a not tested scenario at the moment the idea is to `create`/`destroy` to produce new clusters. Destroy don't remove the buckets of state, only `clean` with a flag would do that for you, if choose, as you may want to store the state for something like recover some info. 

No migration scenarios supported.

**Comment by johndietz** [comment]
Closing issue due to inactivity, please feel free to reopen if help is still needed
