### ISSUE TITLE
GITLAB - Eventual issue when running installer - softserve not ready

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#350]
# Overview 

Some installs seems to fail on this step, it seems to be related to trying to push to gitops too fast, without having it ready to receive the code from gitops. 

```bash 
LOG: 2022/09/09 16:11:02.699911 /home/developer/app/pkg/shell.go:24: ERR:
LOG: 2022/09/09 16:11:02.700336 /home/developer/app/internal/k8s/kubernetes.go:220: soft-serve pods found, continuing
LOG: 2022/09/09 16:11:13.707956 /home/developer/app/cmd/createGitlab.go:86: Waiting for soft-serve installation to complete...
LOG: 2022/09/09 16:11:33.711779 /home/developer/app/cmd/createUtils.go:303: Softserve Update
LOG: 2022/09/09 16:11:33.712881 /home/developer/app/internal/softserve/softserve.go:49: Executing configureSoftserveAndPush
LOG: 2022/09/09 16:11:33.714010 /home/developer/app/internal/softserve/softserve.go:73: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/09 16:11:33.720291 /home/developer/app/internal/softserve/softserve.go:84: error cloning config repository from soft serve
```

**Comment by 6za** [comment]
More info: 
```bash
Prepare Temporary Repo        ... done! [4 in 16m7.385s]
panic: error cloning config repository from soft serve

goroutine 1 [running]:
log.Panicf({0x1c2d404?, 0xc00005a048?}, {0x0?, 0x1a?, 0x1?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/internal/softserve.configureSoftServe()
	/home/developer/app/internal/softserve/softserve.go:84 +0x214
github.com/kubefirst/kubefirst/internal/softserve.ConfigureSoftServeAndPush(0x0)
	/home/developer/app/internal/softserve/softserve.go:55 +0xbd
github.com/kubefirst/kubefirst/cmd.glob..func11(0xc0001a6ea0?, {0xc000548950, 0x0, 0x1})
	/home/developer/app/cmd/createGitlab.go:98 +0x56f
github.com/kubefirst/kubefirst/cmd.glob..func9(0x2b8d800, {0xc000548950?, 0x0, 0x1})
	/home/developer/app/cmd/create.go:49 +0x1d6
github.com/spf13/cobra.(*Command).execute(0x2b8d800, {0xc000548940, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2b8da80)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:26 +0x25
main.main()
	/home/developer/app/main.go:65 +0x41d
```

**Comment by 6za** [comment]
Missing some tests from gitlab to ensure issue is already addressed, I believe a PR was merged in main to add 5 retrials on this issue.

**Comment by 6za** [comment]
PR tested and worked as expected.
