### ISSUE TITLE
GITLAB - Erroring when trying to adopt gitlab

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#351]
# Overview 

Error on gitlab install:

```bash 
LOG: 2022/09/09 16:17:32.282347 /home/developer/app/pkg/shell.go:20: Error executing command: exit status 1
LOG: 2022/09/09 16:17:32.282813 /home/developer/app/pkg/shell.go:22: Command Execution: /home/developer/.k1/tools/kubectl
LOG: 2022/09/09 16:17:32.283273 /home/developer/app/pkg/shell.go:23: OUT:
LOG: 2022/09/09 16:17:32.283639 /home/developer/app/pkg/shell.go:24: ERR: error: the path "/home/developer/.k1/gitops/components/helpers/registry.yaml" does not exist

LOG: 2022/09/09 16:17:32.283874 /home/developer/app/cmd/createGitlab.go:138: failed to call execute kubectl apply of argocd patch to adopt gitlab: exit status 1
```

Panic: 

```bash 
Deploy CI/CD                  ... done! [5 in 1m40.216s]
panic: failed to call execute kubectl apply of argocd patch to adopt gitlab: exit status 1

goroutine 1 [running]:
log.Panicf({0x1c5776e?, 0x21?}, {0xc000125b38?, 0x7?, 0x7?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/cmd.glob..func11(0xc000187520?, {0xc00057e870, 0x0, 0x1})
	/home/developer/app/cmd/createGitlab.go:138 +0x992
github.com/kubefirst/kubefirst/cmd.glob..func9(0x2b8d800, {0xc00057e870?, 0x0, 0x1})
	/home/developer/app/cmd/create.go:49 +0x1d6
github.com/spf13/cobra.(*Command).execute(0x2b8d800, {0xc00057e860, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2b8da80)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:26 +0x25
main.main()
	/home/developer/app/main.go:65 +0x41d
```

**Comment by 6za** [comment]
It seems to be related to recent changes on `gitops` templates.

**Comment by 6za** [comment]
A small fix seems to be missing here for github: 
https://github.com/kubefirst/kubefirst/blob/3041d5f4226fd3705a4d521cce96be6da7963996/internal/argocd/argocd.go#L292


And gitlab: 
https://github.com/kubefirst/kubefirst/blob/3041d5f4226fd3705a4d521cce96be6da7963996/cmd/createGitlab.go#L136

After all the changes on templates, I believe we should only have 1 single registry file and from there all is unfolded.

**Comment by 6za** [comment]
Templates seems to be as expected: https://github.com/kubefirst/gitops-template/compare/1.8.6...main

**Comment by 6za** [comment]
merged. :)
