### ISSUE TITLE
Failed to terraform destroy gitlab with kubefirst destroy

### ISSUE THREAD

**Issue by casperakos** [kubefirst/kubefirst#395]
I created a cluster and then tried to destroy but I'm getting this error:

```
LOG: 2022/09/14 14:29:45.155757 /Users/jdietz/git/github/kubefirst/kubefirst/cmd/init.go:297: init started
Logging at: /Users/elias/Documents/Xandy/Kubefirst/logs/log_1663158585.log
LOG: 2022/09/14 14:29:45.157037 /Users/jdietz/git/github/kubefirst/kubefirst/pkg/helpers.go:132: Using config file: /Users/elias/.kubefirst
Init actions: 2 expected tasks ...

- Open gitlab port-forward
- Open argocd port-forward
- Open vault port-forward
Open Ports                    ... done! [3 in 3.012s]
- Destroying Gitlab
Destroy Cloud                 ... 25.0% [#######.....................] [1 in 7.387512s]
panic: failed to terraform destroy gitlab exit status 1

goroutine 1 [running]:
log.Panicf({0x284abd8?, 0xc000500ae0?}, {0xc00059b9e8?, 0xc00059b9f8?, 0x2?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/internal/gitlab.DestroyGitlabTerraform(0x0)
	/Users/jdietz/git/github/kubefirst/kubefirst/internal/gitlab/gitlab.go:372 +0x70a
github.com/kubefirst/kubefirst/cmd.glob..func7(0x39b1a40?, {0x280adc7?, 0x0?, 0x0?})
	/Users/jdietz/git/github/kubefirst/kubefirst/cmd/destroy.go:113 +0xcef
github.com/spf13/cobra.(*Command).execute(0x39b1a40, {0x39fe120, 0x0, 0x0})
	/Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x39b0dc0)
	/Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/Users/jdietz/git/github/kubefirst/kubefirst/cmd/root.go:26 +0x25
main.main()
	/Users/jdietz/git/github/kubefirst/kubefirst/main.go:65 +0x41d

```

**Comment by 6za** [comment]
If you type `destroy --help`. there are some choices of actions to skip.. 

Is this a second attempt to destroy? did you install was fully finished. If not, you may want to skip the register destroy and the gitlab terraform. 

Based on your error, you may be missing gitlab, so attempt to destroy it would fail.

**Comment by eliastsironis** [comment]
Yep, with kubefirst destroy --skip-gitlab-terraform --skip-delete-register, resources are now have been destroyed. The cluster was not succesfully created at first with this error:

```
Process Parameters            ... done! [1 in 1.002s]
- Creating K8S Cluster
Prepare Temporary Repo        ... 25.0% [#######.....................] [1 in 16.69795s]
panic: error: terraform init failed exit status 1

goroutine 1 [running]:
log.Panic({0xc0004a7440?, 0x2a?, 0xc0004a7420?})
	/usr/local/go/src/log/log.go:385 +0x65
github.com/kubefirst/kubefirst/internal/terraform.ApplyBaseTerraform(0x0, {0xc000048c00, 0x26})
	/Users/jdietz/git/github/kubefirst/kubefirst/internal/terraform/terraform.go:41 +0x585
github.com/kubefirst/kubefirst/cmd.glob..func6(0x39b0b40?, {0x39fe120, 0x0, 0x0})
	/Users/jdietz/git/github/kubefirst/kubefirst/cmd/create.go:78 +0x37b
github.com/spf13/cobra.(*Command).execute(0x39b0b40, {0x39fe120, 0x0, 0x0})
	/Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x39b0dc0)
	/Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/jdietz/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/Users/jdietz/git/github/kubefirst/kubefirst/cmd/root.go:26 +0x25
main.main()
	/Users/jdietz/git/github/kubefirst/kubefirst/main.go:65 +0x41d
```

I will give it another try after a clean the kubefirst config. 

Thanks

**Comment by 6za** [comment]
thank, if you have issues or parts of the previous log you want share, we can help here or in the slack channel. Thanks for reporting the issue and using kubefirst.
