### ISSUE TITLE
1.9.x - gitlab install still takes a while to have softserve ready

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#429]
# Error

```bash 
Init actions: 4 expected tasks ...

Process Parameters            ... done! [1 in 0s]
- Creating K8S Cluster
Prepare Temporary Repo        ... 25.0% [#######.....................] [1 in 13m44.901012s]
- Created Softserve
- Waiting Softserve
Prepare Temporary Repo        ... done! [4 in 14m31.228s]
panic: we tried hard to setup SoftServe but there were something wrong, please check the logs

goroutine 1 [running]:
log.Panic({0xc0000eb888?, 0x1c0f10c?, 0xc0000eb888?})
	/usr/local/go/src/log/log.go:385 +0x65
github.com/kubefirst/kubefirst/internal/softserve.ConfigureSoftServeAndPush(0x0)
	/home/developer/app/internal/softserve/softserve.go:96 +0x316
github.com/kubefirst/kubefirst/cmd.glob..func12(0xc0001056c0?, {0xc000201bf0, 0x0, 0x1})
	/home/developer/app/cmd/createGitlab.go:99 +0x5ff
github.com/kubefirst/kubefirst/cmd.glob..func10(0x2b9fde0, {0xc000201bf0?, 0x0, 0x1})
	/home/developer/app/cmd/create.go:50 +0x1d9
github.com/spf13/cobra.(*Command).execute(0x2b9fde0, {0xc000201be0, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2ba0060)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:26 +0x25
main.main()
	/home/developer/app/main.go:65 +0x41d
```

## Logs
```bash 
LOG: 2022/09/21 12:37:37.814911 /home/developer/app/cmd/createUtils.go:303: Softserve Update
LOG: 2022/09/21 12:37:37.816504 /home/developer/app/internal/softserve/softserve.go:62: Executing configureSoftserveAndPush
LOG: 2022/09/21 12:37:37.817690 /home/developer/app/internal/softserve/softserve.go:68: Configuring SoftServe, attempt (1 of 5)
LOG: 2022/09/21 12:37:37.818605 /home/developer/app/internal/softserve/softserve.go:108: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/21 12:37:37.826373 /home/developer/app/internal/softserve/softserve.go:72: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/21 12:37:47.827344 /home/developer/app/internal/softserve/softserve.go:68: Configuring SoftServe, attempt (2 of 5)
LOG: 2022/09/21 12:37:47.828223 /home/developer/app/internal/softserve/softserve.go:108: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/21 12:37:47.831216 /home/developer/app/internal/softserve/softserve.go:72: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/21 12:37:57.833590 /home/developer/app/internal/softserve/softserve.go:68: Configuring SoftServe, attempt (3 of 5)
LOG: 2022/09/21 12:37:57.834492 /home/developer/app/internal/softserve/softserve.go:108: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/21 12:37:57.837003 /home/developer/app/internal/softserve/softserve.go:72: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/21 12:38:07.838641 /home/developer/app/internal/softserve/softserve.go:68: Configuring SoftServe, attempt (4 of 5)
LOG: 2022/09/21 12:38:07.839527 /home/developer/app/internal/softserve/softserve.go:108: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/21 12:38:07.841958 /home/developer/app/internal/softserve/softserve.go:72: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/21 12:38:17.843676 /home/developer/app/internal/softserve/softserve.go:68: Configuring SoftServe, attempt (5 of 5)
LOG: 2022/09/21 12:38:17.844436 /home/developer/app/internal/softserve/softserve.go:108: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/21 12:38:17.846660 /home/developer/app/internal/softserve/softserve.go:72: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/21 12:38:27.849596 /home/developer/app/internal/softserve/softserve.go:96: we tried hard to setup SoftServe but there were something wrong, please check the logs

```

**Comment by 6za** [comment]
I will add extra checks before proceeding.

**Comment by 6za** [comment]
At this moment of the installation we only have:
- EKS Cluster 
- A manual installation of `soft-serve`

Argo is not around yet.

**Comment by 6za** [comment]
PF may not be working as expected yet.

**Comment by 6za** [comment]
https://github.com/kubefirst/kubefirst/blob/bd552b8b1f3e068d5e9913c680050febecd9dc28/cmd/createGitlab.go#L88 

This block of try to configure `softserve` and `create port forward` needs to be part of a loop, as Config may be failing due to a bad port-forward.

**Comment by 6za** [comment]
#408 fix didn't worked.

**Comment by 6za** [comment]
PR open, tests worked. Waiting approvals, closing issue.

**Comment by 6za** [comment]
Sample of retry rule for soft-serve working as desired, a former fail scenario that was saved with this rule: 
```bash 

LOG: 2022/09/22 18:49:01.689412 /home/developer/app/internal/k8s/kubernetes.go:229: soft-serve pods found, continuing
LOG: 2022/09/22 18:49:11.694271 /home/developer/app/cmd/createGitlab.go:87: Waiting for soft-serve installation to complete...
LOG: 2022/09/22 18:49:11.695377 /home/developer/app/internal/k8s/kubernetes.go:185: PF started (svc/soft-serve)
LOG: 2022/09/22 18:49:16.697909 /home/developer/app/internal/k8s/kubernetes.go:193: /home/developer/.k1/tools/kubectl   --kubeconfig   /home/developer/.k1/gitops/terraform/base/kubeconfig   -n   soft-serve   port-forward   svc/soft-serve   8022:22
LOG: 2022/09/22 18:49:36.699545 /home/developer/app/internal/softserve/softserve.go:62: Executing configureSoftserveAndPush
LOG: 2022/09/22 18:49:36.699858 /home/developer/app/internal/softserve/softserve.go:67: Configuring SoftServe, attempt (1 of 5)
LOG: 2022/09/22 18:49:36.700130 /home/developer/app/internal/softserve/softserve.go:104: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/22 18:49:36.707311 /home/developer/app/internal/softserve/softserve.go:71: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/22 18:49:46.709585 /home/developer/app/internal/softserve/softserve.go:67: Configuring SoftServe, attempt (2 of 5)
LOG: 2022/09/22 18:49:46.710142 /home/developer/app/internal/softserve/softserve.go:104: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/22 18:49:46.712601 /home/developer/app/internal/softserve/softserve.go:71: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/22 18:49:56.713477 /home/developer/app/internal/softserve/softserve.go:67: Configuring SoftServe, attempt (3 of 5)
LOG: 2022/09/22 18:49:56.714057 /home/developer/app/internal/softserve/softserve.go:104: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/22 18:49:56.716746 /home/developer/app/internal/softserve/softserve.go:71: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/22 18:50:06.718479 /home/developer/app/internal/softserve/softserve.go:67: Configuring SoftServe, attempt (4 of 5)
LOG: 2022/09/22 18:50:06.719399 /home/developer/app/internal/softserve/softserve.go:104: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/22 18:50:06.722050 /home/developer/app/internal/softserve/softserve.go:71: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/22 18:50:16.724033 /home/developer/app/internal/softserve/softserve.go:67: Configuring SoftServe, attempt (5 of 5)
LOG: 2022/09/22 18:50:16.724604 /home/developer/app/internal/softserve/softserve.go:104: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/22 18:50:16.726378 /home/developer/app/internal/softserve/softserve.go:71: something went wrong, error is: error cloning config repository from soft serve, error: dial tcp 127.0.0.1:8022: connect: connection refused, going to try again...
LOG: 2022/09/22 18:50:26.727519 /home/developer/app/cmd/createGitlab.go:108: Soft-serve not configured - waiting before trying again
LOG: 2022/09/22 18:50:26.728156 /home/developer/app/cmd/createGitlab.go:109: Soft-serve not configured - Re-creating Port-forward deails at: https://github.com/kubefirst/kubefirst/issues/429
LOG: 2022/09/22 18:50:46.731145 /home/developer/app/internal/k8s/kubernetes.go:185: PF started (svc/soft-serve)
LOG: 2022/09/22 18:50:51.732013 /home/developer/app/internal/k8s/kubernetes.go:193: /home/developer/.k1/tools/kubectl   --kubeconfig   /home/developer/.k1/gitops/terraform/base/kubeconfig   -n   soft-serve   port-forward   svc/soft-serve   8022:22
LOG: 2022/09/22 18:51:11.733719 /home/developer/app/internal/softserve/softserve.go:62: Executing configureSoftserveAndPush
LOG: 2022/09/22 18:51:11.734241 /home/developer/app/internal/softserve/softserve.go:67: Configuring SoftServe, attempt (1 of 5)
LOG: 2022/09/22 18:51:11.734782 /home/developer/app/internal/softserve/softserve.go:104: gitClient clone ssh://127.0.0.1:8022/config /home/developer/.k1/config
LOG: 2022/09/22 18:51:13.619108 /home/developer/app/internal/softserve/softserve.go:133: re-wrote config.yaml at /home/developer/.k1/config folder
LOG: 2022/09/22 18:51:13.619611 /home/developer/app/internal/softserve/softserve.go:140: Committing new changes...
LOG: 2022/09/22 18:51:15.544643 /home/developer/app/pkg/helpers.go:71: trying read the file in yaml format:  /home/deve
```
