### ISSUE TITLE
1.9.x - gitlab install argo cd missing for helm install

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#434]
# Erro

```bash
panic: error: could not helm install argocd command exit status 1

goroutine 1 [running]:
log.Panicf({0x1c3ade3?, 0x1e?}, {0xc0000f3728?, 0xe?, 0xe?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/internal/helm.InstallArgocd(0x0)
	/home/developer/app/internal/helm/helm.go:32 +0x4a5
github.com/kubefirst/kubefirst/cmd.glob..func12(0xc000105860?, {0xc000255ab0, 0x0, 0x1})
	/home/developer/app/cmd/createGitlab.go:105 +0x6af
github.com/kubefirst/kubefirst/cmd.glob..func10(0x2b9fde0, {0xc000255ab0?, 0x0, 0x1})
	/home/developer/app/cmd/create.go:50 +0x1d9
github.com/spf13/cobra.(*Command).execute(0x2b9fde0, {0xc000255a90, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2ba0060)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:26 +0x25
main.main()
```

## Logs

```bash 
LOG: 2022/09/21 16:41:13.815420 /home/developer/app/pkg/shell.go:24: ERR: 
LOG: 2022/09/21 16:41:14.204691 /home/developer/app/pkg/shell.go:22: Command Execution: /home/developer/.k1/tools/helm
LOG: 2022/09/21 16:41:14.205089 /home/developer/app/pkg/shell.go:23: OUT: Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "argo" chart repository
Update Complete. ⎈Happy Helming!⎈

LOG: 2022/09/21 16:41:14.205468 /home/developer/app/pkg/shell.go:24: ERR: 
LOG: 2022/09/21 16:41:22.466552 /home/developer/app/pkg/shell.go:20: Error executing command: exit status 1
LOG: 2022/09/21 16:41:22.466793 /home/developer/app/pkg/shell.go:22: Command Execution: /home/developer/.k1/tools/helm
LOG: 2022/09/21 16:41:22.467031 /home/developer/app/pkg/shell.go:23: OUT: Release "argocd" does not exist. Installing it now.

LOG: 2022/09/21 16:41:22.467216 /home/developer/app/pkg/shell.go:24: ERR: Error: failed to download "argo/argo-cd" at version "4.10.5" (hint: running `helm repo update` may help)

LOG: 2022/09/21 16:41:22.467391 /home/developer/app/internal/helm/helm.go:32: error: could not helm install argocd command exit status 1
```

**Comment by 6za** [comment]
it seems to be due the excess of `panic` calls from the downstream code. I will try to add a retry logic to this operation.

**Comment by 6za** [comment]
PR open, waiting tests.

**Comment by 6za** [comment]
PR tested, worked as expected on github and gitlab
