### ISSUE TITLE
Gitlab install issue

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#445]
# Error

```bash 
Setup Gitlab                  ... 83.3% [#######################.....] [5 in 5m12.970018s]
panic: error: terraform apply for gitlab failed exit status 1

goroutine 1 [running]:
log.Panicf({0x1c33cc0?, 0xc00077e600?}, {0xc0005177a0?, 0xc0001037b0?, 0x2?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/internal/gitlab.ApplyGitlabTerraform(0x0, {0x10?, 0x1bf6c8c?})
	/home/developer/app/internal/gitlab/gitlab.go:288 +0x4f7
github.com/kubefirst/kubefirst/cmd.glob..func12(0xc000142340?, {0xc000266fb0, 0x0, 0x1})
	/home/developer/app/cmd/createGitlab.go:222 +0x11f5
github.com/kubefirst/kubefirst/cmd.glob..func10(0x2ba3de0, {0xc000266fb0?, 0x0, 0x1})
	/home/developer/app/cmd/create.go:50 +0x1d9
github.com/spf13/cobra.(*Command).execute(0x2ba3de0, {0xc000266fa0, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2ba4060)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:26 +0x25
main.main()
	/home/developer/app/main.go:65 +0x41d
```

## Logs

```bash 
LOG: 2022/09/22 18:59:05.549155 /home/developer/app/internal/gitlab/gitlab.go:246: getting gitlab runner token
LOG: 2022/09/22 18:59:05.723150 /home/developer/app/cmd/createUtils.go:303: Gitlab terraform
LOG: 2022/09/22 18:59:05.723555 /home/developer/app/internal/gitlab/gitlab.go:262: Executing applyGitlabTerraform
LOG: 2022/09/22 18:59:05.723835 /home/developer/app/pkg/shell.go:33: INFO: Running /home/developer/.k1/tools/terraform
LOG: 2022/09/22 18:59:05.724096 /home/developer/app/pkg/shell.go:36:  export AWS_SDK_LOAD_CONFIG = 1
LOG: 2022/09/22 18:59:05.724325 /home/developer/app/pkg/shell.go:36:  export AWS_PROFILE = default
LOG: 2022/09/22 18:59:05.724611 /home/developer/app/pkg/shell.go:36:  export GITLAB_TOKEN = <redacted>
LOG: 2022/09/22 18:59:05.724853 /home/developer/app/pkg/shell.go:36:  export GITLAB_BASE_URL = http://localhost:8888
LOG: 2022/09/22 18:59:05.791661 /home/developer/app/pkg/shell.go:61: OUT:  Initializing modules...
LOG: 2022/09/22 18:59:05.794062 /home/developer/app/pkg/shell.go:61: OUT:  - gitops in templates/gitlab-repo
LOG: 2022/09/22 18:59:05.795004 /home/developer/app/pkg/shell.go:61: OUT:  - metaphor in templates/gitlab-repo
LOG: 2022/09/22 18:59:05.795950 /home/developer/app/pkg/shell.go:61: OUT:  - metaphor-frontend in templates/gitlab-repo
LOG: 2022/09/22 18:59:05.797294 /home/developer/app/pkg/shell.go:61: OUT:  - metaphor-go in templates/gitlab-repo
LOG: 2022/09/22 18:59:05.800207 /home/developer/app/pkg/shell.go:61: OUT:
LOG: 2022/09/22 18:59:05.800714 /home/developer/app/pkg/shell.go:61: OUT:  Initializing the backend...
LOG: 2022/09/22 18:59:06.689784 /home/developer/app/pkg/shell.go:61: OUT:
LOG: 2022/09/22 18:59:06.690335 /home/developer/app/pkg/shell.go:61: OUT:  Successfully configured the backend "s3"! Terraform will automatically
LOG: 2022/09/22 18:59:06.690933 /home/developer/app/pkg/shell.go:61: OUT:  use this backend unless the backend configuration changes.
LOG: 2022/09/22 18:59:09.179368 /home/developer/app/pkg/shell.go:61: OUT:
LOG: 2022/09/22 18:59:09.179954 /home/developer/app/pkg/shell.go:61: OUT:  Initializing provider plugins...
LOG: 2022/09/22 18:59:09.180348 /home/developer/app/pkg/shell.go:61: OUT:  - Finding latest version of gitlabhq/gitlab...
LOG: 2022/09/22 18:59:09.603991 /home/developer/app/pkg/shell.go:61: OUT:  - Finding latest version of hashicorp/aws...
LOG: 2022/09/22 18:59:11.131681 /home/developer/app/pkg/shell.go:61: OUT:  - Installing gitlabhq/gitlab v3.18.0...
LOG: 2022/09/22 18:59:12.409265 /home/developer/app/pkg/shell.go:61: OUT:  - Installed gitlabhq/gitlab v3.18.0 (signed by a HashiCorp partner, key ID BC097C3333027B14)
LOG: 2022/09/22 18:59:12.864265 /home/developer/app/pkg/shell.go:61: OUT:  - Installing hashicorp/aws v4.31.0...
LOG: 2022/09/22 18:59:19.624147 /home/developer/app/pkg/shell.go:61: OUT:  - Installed hashicorp/aws v4.31.0 (signed by HashiCorp)
LOG: 2022/09/22 18:59:19.625241 /home/developer/app/pkg/shell.go:61: OUT:
LOG: 2022/09/22 18:59:19.626086 /home/developer/app/pkg/shell.go:61: OUT:  Partner and community providers are signed by their developers.
LOG: 2022/09/22 18:59:19.626852 /home/developer/app/pkg/shell.go:61: OUT:  If you'd like to know more about provider signing, you can read about it here:
LOG: 2022/09/22 18:59:19.627543 /home/developer/app/pkg/shell.go:61: OUT:  https://www.terraform.io/docs/cli/plugins/signing.html
LOG: 2022/09/22 18:59:19.628163 /home/developer/app/pkg/shell.go:61: OUT:
LOG: 2022/09/22 18:59:19.628627 /home/developer/app/pkg/shell.go:61: OUT:  Terraform has created a lock file .terraform.lock.hcl to record the provider
LOG: 2022/09/22 18:59:19.629163 /home/developer/app/pkg/shell.go:61: OUT:  selections it made above. Include this file in your version control repository
LOG: 2022/09/22 18:59:19.629644 /home/developer/app/pkg/shell.go:61: OUT:  so that Terraform can guarantee to make the same selections by default when
LOG: 2022/09/22 18:59:19.629925 /home/developer/app/pkg/shell.go:61: OUT:  you run "terraform init" in the future.
LOG: 2022/09/22 18:59:19.630116 /home/developer/app/pkg/shell.go:61: OUT:
LOG: 2022/09/22 18:59:19.630364 /home/developer/app/pkg/shell.go:61: OUT:  Terraform has been successfully initialized!
LOG: 2022/09/22 18:59:19.630658 /home/developer/app/pkg/shell.go:61: OUT:
LOG: 2022/09/22 18:59:19.631001 /home/developer/app/pkg/shell.go:61: OUT:  You may now begin working with Terraform. Try running "terraform plan" to see
LOG: 2022/09/22 18:59:19.632207 /home/developer/app/pkg/shell.go:61: OUT:  any changes that are required for your infrastructure. All Terraform commands
LOG: 2022/09/22 18:59:19.632744 /home/developer/app/pkg/shell.go:61: OUT:  should now work.
LOG: 2022/09/22 18:59:19.633066 /home/developer/app/pkg/shell.go:61: OUT:
LOG: 2022/09/22 18:59:19.633447 /home/developer/app/pkg/shell.go:61: OUT:  If you ever set or change modules or backend configuration for Terraform,
LOG: 2022/09/22 18:59:19.633687 /home/developer/app/pkg/shell.go:61: OUT:  rerun this command to reinitialize your working directory. If you forget, other
LOG: 2022/09/22 18:59:19.634167 /home/developer/app/pkg/shell.go:61: OUT:  commands will detect it and remind you to do so if necessary.
LOG: 2022/09/22 18:59:19.636083 /home/developer/app/pkg/shell.go:33: INFO: Running /home/developer/.k1/tools/terraform
LOG: 2022/09/22 18:59:19.636655 /home/developer/app/pkg/shell.go:36:  export GITLAB_BASE_URL = http://localhost:8888
LOG: 2022/09/22 18:59:19.636968 /home/developer/app/pkg/shell.go:36:  export AWS_SDK_LOAD_CONFIG = 1
LOG: 2022/09/22 18:59:19.637191 /home/developer/app/pkg/shell.go:36:  export AWS_PROFILE = default
LOG: 2022/09/22 18:59:19.637623 /home/developer/app/pkg/shell.go:36:  export GITLAB_TOKEN = <redacted>
LOG: 2022/09/22 18:59:26.710529 /home/developer/app/pkg/shell.go:67: ERR:  ╷
LOG: 2022/09/22 18:59:26.711023 /home/developer/app/pkg/shell.go:67: ERR:  │ Error: Invalid provider configuration
LOG: 2022/09/22 18:59:26.711819 /home/developer/app/pkg/shell.go:67: ERR:  │
LOG: 2022/09/22 18:59:26.712203 /home/developer/app/pkg/shell.go:67: ERR:  │ Provider "registry.terraform.io/gitlabhq/gitlab" requires explicit
LOG: 2022/09/22 18:59:26.712799 /home/developer/app/pkg/shell.go:67: ERR:  │ configuration. Add a provider block to the root module and configure the
LOG: 2022/09/22 18:59:26.713191 /home/developer/app/pkg/shell.go:67: ERR:  │ provider's required arguments as described in the provider documentation.
LOG: 2022/09/22 18:59:26.713789 /home/developer/app/pkg/shell.go:67: ERR:  │
LOG: 2022/09/22 18:59:26.714455 /home/developer/app/pkg/shell.go:67: ERR:  ╵
LOG: 2022/09/22 18:59:26.714806 /home/developer/app/pkg/shell.go:67: ERR:  ╷
LOG: 2022/09/22 18:59:26.715382 /home/developer/app/pkg/shell.go:67: ERR:  │ Error: Get "http://localhost:8888/api/v4/user": dial tcp 127.0.0.1:8888: connect: connection refused
LOG: 2022/09/22 18:59:26.715706 /home/developer/app/pkg/shell.go:67: ERR:  │
LOG: 2022/09/22 18:59:26.716246 /home/developer/app/pkg/shell.go:67: ERR:  │   with provider["registry.terraform.io/gitlabhq/gitlab"],
LOG: 2022/09/22 18:59:26.716580 /home/developer/app/pkg/shell.go:67: ERR:  │   on <empty> line 0:
LOG: 2022/09/22 18:59:26.717431 /home/developer/app/pkg/shell.go:67: ERR:  │   (source code not available)
LOG: 2022/09/22 18:59:26.717839 /home/developer/app/pkg/shell.go:67: ERR:  │
LOG: 2022/09/22 18:59:26.718292 /home/developer/app/pkg/shell.go:67: ERR:  ╵
LOG: 2022/09/22 18:59:26.751428 /home/developer/app/pkg/shell.go:74: error: /home/developer/.k1/tools/terraform failed exit status 1
LOG: 2022/09/22 18:59:26.751887 /home/developer/app/internal/gitlab/gitlab.go:288: error: terraform apply for gitlab failed exit status 1

```

**Comment by 6za** [comment]
It seems to be a "broken port-forward".  Retrying to run installer should work.

**Comment by 6za** [comment]
Retry fails: 
```
LOG: 2022/09/22 19:02:51.446581 /home/developer/app/cmd/createGitlab.go:105: Soft-serve configured
LOG: 2022/09/22 19:02:51.447308 /home/developer/app/cmd/createUtils.go:303: Softserve Update
LOG: 2022/09/22 19:02:51.447943 /home/developer/app/cmd/createUtils.go:303: Deploy ArgoCD
LOG: 2022/09/22 19:02:51.448622 /home/developer/app/cmd/createGitlab.go:122: Error installing argocd
```

It seems to be impacted by new code.

**Comment by 6za** [comment]
tested fix, working.
