### ISSUE TITLE
gitlab - install issue

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#477]
# Logs

```bash
LOG: 2022/09/29 14:04:50.704173 /home/developer/app/pkg/shell.go:69: ERR:  ╷
LOG: 2022/09/29 14:04:50.704755 /home/developer/app/pkg/shell.go:69: ERR:  │ Error: error creating role "KubernetesDeveloper" for backend "aws": Error making API request.
LOG: 2022/09/29 14:04:50.705272 /home/developer/app/pkg/shell.go:69: ERR:  │
LOG: 2022/09/29 14:04:50.705698 /home/developer/app/pkg/shell.go:69: ERR:  │ URL: PUT http://localhost:8200/v1/aws/roles/KubernetesDeveloper
LOG: 2022/09/29 14:04:50.706130 /home/developer/app/pkg/shell.go:69: ERR:  │ Code: 404. Errors:
LOG: 2022/09/29 14:04:50.706618 /home/developer/app/pkg/shell.go:69: ERR:  │
LOG: 2022/09/29 14:04:50.706980 /home/developer/app/pkg/shell.go:69: ERR:  │ * no handler for route "aws/roles/KubernetesDeveloper". route entry not found.
LOG: 2022/09/29 14:04:50.707401 /home/developer/app/pkg/shell.go:69: ERR:  │
LOG: 2022/09/29 14:04:50.707739 /home/developer/app/pkg/shell.go:69: ERR:  │   with vault_aws_secret_backend_role.developer,
LOG: 2022/09/29 14:04:50.708017 /home/developer/app/pkg/shell.go:69: ERR:  │   on aws-auth-backend.tf line 21, in resource "vault_aws_secret_backend_role" "developer":
LOG: 2022/09/29 14:04:50.708319 /home/developer/app/pkg/shell.go:69: ERR:  │   21: resource "vault_aws_secret_backend_role" "developer" {
LOG: 2022/09/29 14:04:50.708636 /home/developer/app/pkg/shell.go:69: ERR:  │
LOG: 2022/09/29 14:04:50.709150 /home/developer/app/pkg/shell.go:69: ERR:  ╵
LOG: 2022/09/29 14:04:50.726486 /home/developer/app/pkg/shell.go:76: error: /home/developer/.k1/tools/terraform failed exit status 1
LOG: 2022/09/29 14:04:50.726917 /home/developer/app/internal/vault/vault.go:113: error: terraform apply failed exit status 1


```

# Error:

```bash 
- Gitlab available at http://localhost:8888
- Gitlab setup tokens
- Gitlab terraform
Setup Gitlab                  ... done! [6 in 5m22.853s]
- Gitlab ready
- waiting for vault unseal
Configure Vault               ...  0.0% [............................] [0 in 35.243186s]
panic: error: terraform apply failed exit status 1

goroutine 1 [running]:
log.Panicf({0x1c15a2f?, 0xc0006e8570?}, {0xc0004d1588?, 0xc0004d15b8?, 0x2?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/internal/vault.ConfigureVault(0x0)
	/home/developer/app/internal/vault/vault.go:113 +0xf2d
github.com/kubefirst/kubefirst/cmd.glob..func14(0xc000172680?, {0xc0004c68e0, 0x0, 0x1})
	/home/developer/app/cmd/createGitlab.go:245 +0x1613
github.com/kubefirst/kubefirst/cmd.glob..func12(0x2b9eac0?, {0xc0004c68e0, 0x0, 0x1})
	/home/developer/app/cmd/create.go:44 +0x1bc
github.com/spf13/cobra.(*Command).execute(0x2b9eac0, {0xc0004c68d0, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2b9ed40)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:26 +0x25
main.main()
	/home/developer/app/main.go:65 +0x41d
```

**Comment by 6za** [comment]
# Earlier log:
```bash 
LOG: 2022/09/29 14:02:37.749721 /home/developer/app/internal/gitlab/gitlab.go:237: generating gitlab personal access token
LOG: 2022/09/29 14:02:37.749967 /home/developer/app/internal/gitlab/gitlab.go:65: generating gitlab personal access token on pod:  gitlab-toolbox-67645dd699-f68mm
LOG: 2022/09/29 14:03:27.529382 /home/developer/app/pkg/shell.go:23: Command Execution: /home/developer/.k1/tools/kubectl
LOG: 2022/09/29 14:03:27.529730 /home/developer/app/pkg/shell.go:24: OUT: 
LOG: 2022/09/29 14:03:27.530083 /home/developer/app/pkg/shell.go:25: ERR: 
LOG: 2022/09/29 14:03:27.534001 /home/developer/app/internal/gitlab/gitlab.go:78: gitlab personal access token generated supressed
LOG: 2022/09/29 14:03:27.534192 /home/developer/app/internal/gitlab/gitlab.go:246: getting gitlab runner token
LOG: 2022/09/29 14:03:27.706479 /home/developer/app/cmd/createUtils.go:303: Gitlab terraform
LOG: 2022/09/29 14:03:27.706788 /home/developer/app/internal/gitlab/gitlab.go:262: Executing applyGitlabTerraform
LOG: 2022/09/29 14:03:27.707113 /home/developer/app/pkg/shell.go:34: INFO: Running /home/developer/.k1/tools/terraform
LOG: 2022/09/29 14:03:27.707365 /home/developer/app/pkg/shell.go:38:  export AWS_SDK_LOAD_CONFIG = *
LOG: 2022/09/29 14:03:27.707717 /home/developer/app/pkg/shell.go:38:  export AWS_PROFILE = *******
LOG: 2022/09/29 14:03:27.707978 /home/developer/app/pkg/shell.go:38:  export GITLAB_TOKEN = ********************
LOG: 2022/09/29 14:03:27.708266 /home/developer/app/pkg/shell.go:38:  export GITLAB_BASE_URL = *********************
LOG: 2022/09/29 14:03:27.767583 /home/developer/app/pkg/shell.go:63: OUT:  [0m[1mInitializing modules...[0m
```

**Comment by 6za** [comment]
It works as expected, it was missing install parameters for dev mode.. the branches in test.
