### ISSUE TITLE
git lab install - issue on wait gitlab

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#541]
Exits: 

```bash
panic: failed to execute kubectl wait for gitlab pods with label app=webservice:
exit status 1

goroutine 1 [running]:
log.Panicf({0x1c8d409?, 0x21?}, {0xc000bed5e0?, 0xa?, 0xc0006c4c00?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/internal/k8s.WaitForGitlab(0xd8?, 0xc0003b3080)
	/home/developer/app/internal/k8s/kubernetes.go:301 +0x2db
github.com/kubefirst/kubefirst/cmd.glob..func16(0xc0001f0000?, {0xc000014ad0, 0x0, 0x1})
	/home/developer/app/cmd/createGitlab.go:211 +0x12c8
github.com/kubefirst/kubefirst/cmd.glob..func13(0x2be1300?, {0xc000014ad0, 0x0, 0x1})
	/home/developer/app/cmd/create.go:90 +0x43f
github.com/spf13/cobra.(*Command).execute(0x2be1300, {0xc000014ac0, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2be1580)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:32 +0x25
main.main() 
```

## Logs: 

```bash 
LOG: 2022/10/10 11:46:53.453740 /home/developer/app/pkg/shell.go:25: ERR:
LOG: 2022/10/10 11:46:53.453983 /home/developer/app/cmd/createUtils.go:253: gitlab namespace found, continuing
LOG: 2022/10/10 11:46:59.055977 /home/developer/app/pkg/shell.go:23: Command Execution: /home/developer/.k1/tools/kubectl
LOG: 2022/10/10 11:46:59.056348 /home/developer/app/pkg/shell.go:24: OUT:
LOG: 2022/10/10 11:46:59.056615 /home/developer/app/pkg/shell.go:25: ERR: No resources found in gitlab namespace.

LOG: 2022/10/10 11:46:59.056855 /home/developer/app/cmd/createUtils.go:265: gitlab pods found, continuing
LOG: 2022/10/10 11:47:14.058128 /home/developer/app/cmd/createGitlab.go:210: waiting for gitlab
LOG: 2022/10/10 11:47:14.830863 /home/developer/app/internal/k8s/kubernetes.go:301: failed to execute kubectl wait for gitlab pods with label app=webservice:
exit status 1
```

**Comment by 6za** [comment]
Re-run install doesn't work.

**Comment by 6za** [comment]
Available pods:

```bash 
argocd                      argocd-application-controller-0                              1/1     Running     0          9m52s
argocd                      argocd-applicationset-controller-5f7bb49c47-jv5wl            1/1     Running     0          9m52s
argocd                      argocd-dex-server-578545c8f7-6wgzd                           1/1     Running     0          9m52s
argocd                      argocd-notifications-controller-6cc67cbcfc-nfd9w             1/1     Running     0          9m52s
argocd                      argocd-redis-78954b8d7-s44zk                                 1/1     Running     0          9m52s
argocd                      argocd-repo-server-6cfd8fc985-48n8t                          1/1     Running     0          9m52s
argocd                      argocd-server-59d4d94db8-dlckx                               1/1     Running     0          9m52s
argocd                      external-secrets-operator-components-wait-xvg9s              0/1     Completed   0          8m36s
argocd                      vault-components-wait-7lsrs                                  1/1     Running     0          8m36s
cert-manager                cert-manager-57d89b9548-64h7n                                1/1     Running     0          8m35s
cert-manager                cert-manager-cainjector-5bcf77b697-kdc2z                     1/1     Running     0          8m35s
cert-manager                cert-manager-webhook-8687fc66d4-cvq28                        1/1     Running     0          8m35s
external-dns                external-dns-7cd47459d4-7527d                                1/1     Running     0          8m41s
external-secrets-operator   external-secrets-operator-754754dfbb-dx8pf                   1/1     Running     0          8m25s
external-secrets-operator   external-secrets-operator-cert-controller-64fb84c4dd-64gmc   1/1     Running     0          8m25s
external-secrets-operator   external-secrets-operator-webhook-889c56c7b-bfhmg            1/1     Running     0          8m25s
ingress-nginx               ingress-nginx-controller-777cccdc76-vsj6p                    1/1     Running     0          8m41s
kube-system                 aws-node-6t6kn                                               1/1     Running     0          15m
kube-system                 aws-node-9x222                                               1/1     Running     0          14m
kube-system                 aws-node-bcqlc                                               1/1     Running     0          15m
kube-system                 aws-node-c8f4r                                               1/1     Running     0          15m
kube-system                 aws-node-lxb2v                                               1/1     Running     0          14m
kube-system                 aws-node-pgxdv                                               1/1     Running     0          15m
kube-system                 aws-node-t6htb                                               1/1     Running     0          15m
kube-system                 coredns-65bfc5645f-cwctf                                     1/1     Running     0          19m
kube-system                 coredns-65bfc5645f-m88tx                                     1/1     Running     0          19m
kube-system                 kube-proxy-5b6zn                                             1/1     Running     0          15m
kube-system                 kube-proxy-jvkps                                             1/1     Running     0          14m
kube-system                 kube-proxy-lgklk                                             1/1     Running     0          15m
kube-system                 kube-proxy-lptpq                                             1/1     Running     0          14m
kube-system                 kube-proxy-p7hz9                                             1/1     Running     0          15m
kube-system                 kube-proxy-sxscz                                             1/1     Running     0          15m
kube-system                 kube-proxy-vh4vr                                             1/1     Running     0          15m
soft-serve                  soft-serve-0                                                 1/1     Running     0          13m
vault                       cm-acme-http-solver-z6jtf                                    1/1     Running     0          7m56s
vault                       unseal-vault-2d98v                                           1/1     Running     0          8m36s
vault                       vault-0                                                      1/1     Running     0          8m30s
vault                       vault-1                                                      1/1     Running     0          8m30s
vault                       vault-2                                                      1/1     Running     0          8m30s
vault                       vault-agent-injector-7587754c5-wj5vv                         1/1     Running     0          8m30s
```

**Comment by 6za** [comment]
![image](https://user-images.githubusercontent.com/53096417/194861289-373e59a9-dd08-4f58-9845-74a0c2045a2c.png)

**Comment by 6za** [comment]
Files on registry:
```
-rw-r--r-- 1 developer developer  681 Oct 10 11:42 atlantis.yaml
-rw-r--r-- 1 developer developer  606 Oct 10 11:42 aws-auth.yaml
-rw-r--r-- 1 developer developer  518 Oct 10 11:42 cert-issuers.yaml
-rw-r--r-- 1 developer developer  533 Oct 10 11:42 cert-manager.yaml
-rw-r--r-- 1 developer developer  584 Oct 10 11:42 chartmuseum.yaml
-rw-r--r-- 1 developer developer  608 Oct 10 11:42 clusterrolebinding.yaml
-rw-r--r-- 1 developer developer  573 Oct 10 11:42 development.yaml
-rw-r--r-- 1 developer developer  659 Oct 10 11:42 external-dns.yaml
-rw-r--r-- 1 developer developer  589 Oct 10 11:42 external-secrets-for-argocd.yaml
-rw-r--r-- 1 developer developer 1264 Oct 10 11:42 external-secrets-operator.yaml
-rw-r--r-- 1 developer developer 1150 Oct 10 11:42 external-secrets-store.yaml
-rw-r--r-- 1 developer developer  931 Oct 10 11:42 ingress-nginx.yaml
-rw-r--r-- 1 developer developer  570 Oct 10 11:42 production.yaml
-rw-r--r-- 1 developer developer  561 Oct 10 11:42 staging.yaml
-rw-r--r-- 1 developer developer 1124 Oct 10 11:42 vault.yaml 
```
