### ISSUE TITLE
Telemetry with segment - seems to not be honor skip telemetry flag

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#575]
`./kubefirst init --admin-email email@kubeshop.io --cloud k3d --github-user user --github-org org --use-telemetry false`
Result: 
```
2022/10/18 11:09:27 kubefirst started
Logging at: /app/logs/log_1666091367.log
LOG: 2022/10/18 11:09:27.892846 /app/pkg/helpers.go:270: Using config file: /Users/6zacode/_tmp_k3d_user/.kubefirst
-----------


  ----------------------------------------------------------------------
  Info summary:
  ----------------------------------------------------------------------

  Operational System: linux
  Architecture: amd64
  Go Lang version: vgo1.18.7
  Kubefirst config file: /Users/6zacode/_tmp_k3d_user/.kubefirst
  Kubefirst config folder: /Users/6zacode/_tmp_k3d_user/.k1
  Kubectl path: /Users/6zacode/_tmp_k3d_user/.k1/tools/kubectl
  Terraform path: /Users/6zacode/_tmp_k3d_user/.k1/tools/terraform
  Kubeconfig path:
  /Users/6zacode/_tmp_k3d_user/.k1/gitops/terraform/base/kubeconfig
  Kubefirst Version: 1.9.8



Init actions: 4 expected tasks ...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x181831d]

goroutine 1 [running]:
github.com/kubefirst/kubefirst/internal/handlers.TelemetryHandler.SendCountMetric(...)
	/app/internal/handlers/telemetry.go:24
github.com/kubefirst/kubefirst/cmd.glob..func26(0x2be5d00?, {0xc00047aa00?, 0xa?, 0xa?})
	/app/cmd/init.go:101 +0x7bd
github.com/spf13/cobra.(*Command).execute(0x2be5d00, {0xc00047a8c0, 0xa, 0xa})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2be7600)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/app/cmd/root.go:32 +0x25
main.main()
	/app/main.go:66 +0x41d
```

**Comment by converge** [comment]
fixed at #574
