### ISSUE TITLE
Bug: Local install - Fail to run:

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#633]
Installer for local failing on code from main. 

## Logs
```bash 
LOG: 2022/11/01 13:55:05.132154 /app/configs/kubefirstDirectory.go:18: ".k1" directory found: /Users/6zacode/_tmp_k3d_user/.k1
LOG: 2022/11/01 13:55:05.132857 /app/cmd/createUtils.go:295: Creating github resources with terraform
LOG: 2022/11/01 13:55:05.133479 /app/internal/terraform/terraform.go:279: Entered InitApplyGithubTerraform
LOG: 2022/11/01 13:55:05.133895 /app/internal/terraform/terraform.go:283: Executing InitApplyGithubTerraform
...
Github token was generated. 
...  
LOG: 2022/11/01 13:55:11.127226 /app/pkg/shell.go:63: OUT:  [1m  # module.gitops.github_repository.repo[0m will be created[0m[0m
LOG: 2022/11/01 13:55:11.127431 /app/pkg/shell.go:63: OUT:  [0m  [32m+[0m[0m resource "github_repository" "repo" {
LOG: 2022/11/01 13:55:11.127608 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mallow_auto_merge[0m[0m       = false
LOG: 2022/11/01 13:55:11.127787 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mallow_merge_commit[0m[0m     = true
LOG: 2022/11/01 13:55:11.127966 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mallow_rebase_merge[0m[0m     = true
LOG: 2022/11/01 13:55:11.128146 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mallow_squash_merge[0m[0m     = true
LOG: 2022/11/01 13:55:11.128326 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0marchive_on_destroy[0m[0m     = false
LOG: 2022/11/01 13:55:11.128567 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0marchived[0m[0m               = false
LOG: 2022/11/01 13:55:11.128760 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mauto_init[0m[0m              = false
LOG: 2022/11/01 13:55:11.128950 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mbranches[0m[0m               = (known after apply)
LOG: 2022/11/01 13:55:11.129141 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mdefault_branch[0m[0m         = (known after apply)
LOG: 2022/11/01 13:55:11.129329 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mdelete_branch_on_merge[0m[0m = true
LOG: 2022/11/01 13:55:11.129657 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0metag[0m[0m                   = (known after apply)
LOG: 2022/11/01 13:55:11.129874 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mfull_name[0m[0m              = (known after apply)
LOG: 2022/11/01 13:55:11.130080 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mgit_clone_url[0m[0m          = (known after apply)
LOG: 2022/11/01 13:55:11.130294 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mhas_issues[0m[0m             = true
LOG: 2022/11/01 13:55:11.130507 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mhtml_url[0m[0m               = (known after apply)
LOG: 2022/11/01 13:55:11.130734 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mhttp_clone_url[0m[0m         = (known after apply)
LOG: 2022/11/01 13:55:11.130940 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mid[0m[0m                     = (known after apply)
LOG: 2022/11/01 13:55:11.131147 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mis_template[0m[0m            = false
LOG: 2022/11/01 13:55:11.131351 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mname[0m[0m                   = "gitops"
LOG: 2022/11/01 13:55:11.131607 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mnode_id[0m[0m                = (known after apply)
LOG: 2022/11/01 13:55:11.131813 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mprivate[0m[0m                = (known after apply)
LOG: 2022/11/01 13:55:11.132007 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mrepo_id[0m[0m                = (known after apply)
LOG: 2022/11/01 13:55:11.132210 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mssh_clone_url[0m[0m          = (known after apply)
LOG: 2022/11/01 13:55:11.132433 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0msvn_url[0m[0m                = (known after apply)
LOG: 2022/11/01 13:55:11.132643 /app/pkg/shell.go:63: OUT:        [32m+[0m [0m[1m[0mvisibility[0m[0m             = "private"
LOG: 2022/11/01 13:55:11.132826 /app/pkg/shell.go:63: OUT:      }
LOG: 2022/11/01 13:55:11.133031 /app/pkg/shell.go:63: OUT:  
LOG: 2022/11/01 13:55:11.133242 /app/pkg/shell.go:63: OUT:  [0m[1mPlan:[0m 3 to add, 0 to change, 0 to destroy.
LOG: 2022/11/01 13:55:11.623801 /app/pkg/shell.go:63: OUT:  [0m[0m[1mgithub_user_ssh_key.kubefirst_bot: Creating...[0m[0m
LOG: 2022/11/01 13:55:11.626711 /app/pkg/shell.go:63: OUT:  [0m[1mmodule.gitops.github_repository.repo: Creating...[0m[0m
LOG: 2022/11/01 13:55:13.197206 /app/pkg/shell.go:63: OUT:  [0m[1mgithub_user_ssh_key.kubefirst_bot: Creation complete after 1s [id=73156436][0m
LOG: 2022/11/01 13:55:13.462531 /app/pkg/shell.go:69: ERR:  [31m╷[0m[0m
LOG: 2022/11/01 13:55:13.462864 /app/pkg/shell.go:69: ERR:  [31m│[0m [0m[1m[31mError: [0m[0m[1mPOST https://api.github.com/user/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already exists on this account}][0m
LOG: 2022/11/01 13:55:13.463172 /app/pkg/shell.go:69: ERR:  [31m│[0m [0m
LOG: 2022/11/01 13:55:13.463514 /app/pkg/shell.go:69: ERR:  [31m│[0m [0m[0m  with module.gitops.github_repository.repo,
LOG: 2022/11/01 13:55:13.463837 /app/pkg/shell.go:69: ERR:  [31m│[0m [0m  on modules/repository/main.tf line 26, in resource "github_repository" "repo":
LOG: 2022/11/01 13:55:13.464073 /app/pkg/shell.go:69: ERR:  [31m│[0m [0m  26: resource "github_repository" "repo" [4m{[0m[0m
LOG: 2022/11/01 13:55:13.464340 /app/pkg/shell.go:69: ERR:  [31m│[0m [0m
LOG: 2022/11/01 13:55:13.464611 /app/pkg/shell.go:69: ERR:  [31m╵[0m[0m
LOG: 2022/11/01 13:55:13.474518 /app/pkg/shell.go:76: error: /Users/6zacode/_tmp_k3d_user/.k1/tools/terraform failed exit status 1
LOG: 2022/11/01 13:55:13.474840 /app/internal/terraform/terraform.go:302: error: terraform apply -auto-approve for /Users/6zacode/_tmp_k3d_user/.k1/gitops/terraform/github failed exit status 1
LOG: 2022/11/01 13:55:13.475279 /app/cmd/create.go:47: [000] Create duration is 13.350386289s
```

## Error
```bash 

Init actions: 8 expected tasks ...

Process Parameters            ... done! [1 in 0s]
- init is done!

- Creating github resources with terraform
Setup gitops on github        ...  0.0% [............................] [0 in 8.287177s]
Setup base cluster            ...  0.0% [............................] [0 in 8.2872s]
Install apps to cluster       ...  0.0% [............................] [0 in 8.287213s]
panic: error: terraform apply -auto-approve for /Users/6zacode/_tmp_k3d_user/.k1/gitops/terraform/github failed exit status 1

goroutine 1 [running]:
log.Panicf({0x1cbf2c6?, 0x38?}, {0xc0005ed490?, 0xc0005ed450?, 0x2?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/internal/terraform.initActionAutoApprove(0x0, {0x1c62be6, 0x5}, {0xc000796900, 0x38})
	/app/internal/terraform/terraform.go:302 +0x6bb
github.com/kubefirst/kubefirst/internal/terraform.InitApplyAutoApprove(...)
	/app/internal/terraform/terraform.go:312
github.com/kubefirst/kubefirst/cmd.glob..func15(0xc000184340?, {0x2ccded8, 0x0, 0x0})
	/app/cmd/createGithubK3d.go:62 +0x28a
github.com/kubefirst/kubefirst/cmd.glob..func13(0xc000184340?, {0x2ccded8, 0x0, 0x0})
	/app/cmd/create.go:118 +0x5ab
github.com/kubefirst/kubefirst/cmd.glob..func30(0x2c80240?, {0x2ccded8, 0x0, 0x0})
	/app/cmd/local.go:52 +0x226
github.com/spf13/cobra.(*Command).execute(0x2c80240, {0x2ccded8, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2c804c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/app/cmd/root.go:32 +0x25
main.main()
	/app/main.go:65 +0x41d
```

**Comment by 6za** [comment]
Side note, logs are printing the token: `LOG: 2022/11/01 13:55:05.134420 /app/internal/terraform/terraform.go:289: tf env vars:  map[GITHUB_OWNER:kxdroid GITHUB_TOKEN:gho...` we need to suppress this line to be logged.

**Comment by converge** [comment]
maybe there is already a gitops repo. in your account 

```LOG: 2022/11/01 13:55:13.462864 /app/pkg/shell.go:69: ERR:  �[31m│�[0m �[0m�[1m�[31mError: �[0m�[0m�[1mPOST https://api.github.com/user/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already exists on this account}]�[0m```

does deleting the repos (gitops,  metaphor's) fix the issue?

**Comment by 6za** [comment]
That is the funny thing, I follow the docs, I just run the command. No flags...  I was expecting to pass a flog with my org or something. 

There, I think we tried to create the repos on the wrong place or something. Let me check my users..

**Comment by 6za** [comment]
no repos that could conflict there: 
![image](https://user-images.githubusercontent.com/53096417/199252470-8925d765-c3f2-46fc-af74-c4f8a628c9e3.png)

**Comment by 6za** [comment]
Do we still support orgs? or only users now?

**Comment by 6za** [comment]
Let me read the doc changes, to get updated on the changes.

**Comment by 6za** [comment]
https://kubefirst.io/blog/kubefirst-v110-release-notes

**Comment by 6za** [comment]
This is probably an old issue, already addressed on newer releases.
