### ISSUE TITLE
CI - Testing Gitlab Failing on CI

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#666]
Branch: `issue_638`

Error: 

```bash 
Init actions: 4 expected tasks ...
Creating K8S Cluster
panic: error: terraform apply failed exit status 1
goroutine 1 [running]:
log.Panic({0xc00014f348?, 0x2b?, 0xc00014f328?})
        /usr/local/go/src/log/log.go:388 +0x65
github.com/kubefirst/kubefirst/internal/terraform.ApplyBaseTerraform(0x0, {0xc000143fa0, 0x1f})
        /src/kubefirst/internal/terraform/terraform.go:141 +0x5b9
github.com/kubefirst/kubefirst/cmd.glob..func16(0xc000107860?, {0xc000362580, 0x0, 0x1})
        /src/kubefirst/cmd/createGitlab.go:67 +0x35c
github.com/kubefirst/kubefirst/cmd.glob..func13(0x2cdb360?, {0xc000362580, 0x0, 0x1})
        /src/kubefirst/cmd/create.go:139 +0x782
github.com/spf13/cobra.(*Command).execute(0x2cdb360, {0xc000362560, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2cdb860)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
        /src/kubefirst/cmd/root.go:33 +0x25
main.main()
        /src/kubefirst/main.go:65 +0x41d

```

## Logs

```bash 
LOG: 2022/11/04 19:34:11.173272 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m[1m[31mError: [0m[0m[1merror waiting for EKS Node Group (6zraykubefirsttech5:mgmt-nodes) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
LOG: 2022/11/04 19:34:11.173281 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m	* i-0172b5eab8ac78153, i-045adf92bad6a39ce, i-0477051b4b81e143c, i-0704fe7f8232f455d, i-0a593b7f7cea149f4, i-0c73f3b19d028cb3b, i-0fcfa7d3999c12324: NodeCreationFailure: Instances failed to join the kubernetes cluster
LOG: 2022/11/04 19:34:11.173285 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m
LOG: 2022/11/04 19:34:11.173291 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m[0m
LOG: 2022/11/04 19:34:11.173296 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m
LOG: 2022/11/04 19:34:11.173302 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m[0m  with module.eks.aws_eks_node_group.mgmt_nodes,
LOG: 2022/11/04 19:34:11.173307 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m  on eks/main.tf line 206, in resource "aws_eks_node_group" "mgmt_nodes":
LOG: 2022/11/04 19:34:11.173312 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m 206: resource "aws_eks_node_group" "mgmt_nodes" [4m{[0m[0m
LOG: 2022/11/04 19:34:11.173316 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m
LOG: 2022/11/04 19:34:11.173323 /src/kubefirst/pkg/shell.go:69: ERR:  [31m╵[0m[0m
LOG: 2022/11/04 19:34:11.192812 /src/kubefirst/pkg/shell.go:69: ERR:  [31m╷[0m[0m
LOG: 2022/11/04 19:34:11.192853 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m[1m[31mError: [0m[0m[1mcreating EC2 NAT Gateway: NatGatewayLimitExceeded: Performing this operation would exceed the limit of 5 NAT gateways
LOG: 2022/11/04 19:34:11.192868 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m	status code: 400, request id: fc878ebd-4a1d-4817-975b-f6e0ca39f8ae[0m
LOG: 2022/11/04 19:34:11.192873 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m
LOG: 2022/11/04 19:34:11.192878 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m[0m  with module.eks.module.vpc.aws_nat_gateway.this[0],
LOG: 2022/11/04 19:34:11.192889 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m  on .terraform/modules/eks.vpc/main.tf line 1018, in resource "aws_nat_gateway" "this":
LOG: 2022/11/04 19:34:11.192894 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m1018: resource "aws_nat_gateway" "this" [4m{[0m[0m
LOG: 2022/11/04 19:34:11.192898 /src/kubefirst/pkg/shell.go:69: ERR:  [31m│[0m [0m
LOG: 2022/11/04 19:34:11.192904 /src/kubefirst/pkg/shell.go:69: ERR:  [31m╵[0m[0m
LOG: 2022/11/04 19:34:11.212027 /src/kubefirst/pkg/shell.go:76: error: /root/.k1/tools/terraform failed exit status 1
LOG: 2022/11/04 19:34:11.212050 /src/kubefirst/internal/terraform/terraform.go:141: error: terraform apply failed exit status 1
LOG: 2022/11/04 19:34:11.212079 /src/kubefirst/cmd/create.go:47: [000] Create duration is 34m29.837912251s
```

**Comment by 6za** [comment]
It seems to be some AWS side limitation. Let's try to change region for the next layer of tests.
