### ISSUE TITLE
gitlab install - some terraform issue

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#785]
# Output
```bash 
- Gitlab terraform
Setup Gitlab                  ... done! [6 in 5m25.23s]
- Gitlab ready
- waiting for vault unseal
Configure Vault               ...  0.0% [............................] [0 in 62.105ms]
panic: error: terraform init failed exit status 1

goroutine 1 [running]:
log.Panicf({0x1cf8fb7?, 0xc0005e1620?}, {0xc0005b72a0?, 0xc0005b7290?, 0x1?})
	/usr/local/go/src/log/log.go:392 +0x67
github.com/kubefirst/kubefirst/internal/vault.ConfigureVault(0x0)
	/home/developer/app/internal/vault/vault.go:116 +0xee5
github.com/kubefirst/kubefirst/cmd.glob..func13(0xc0001e4b60?, {0x2d67858, 0x0, 0x0})
	/home/developer/app/cmd/createGitlab.go:234 +0x156f
github.com/kubefirst/kubefirst/cmd.glob..func11(0x2d19860?, {0x2d67858, 0x0, 0x0})
	/home/developer/app/cmd/create.go:152 +0x93f
github.com/spf13/cobra.(*Command).execute(0x2d19860, {0x2d67858, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2d19ae0)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:37 +0x25
main.main()
	/home/developer/app/main.go:65 +0x41d
```

# Logs 
```bash 
LOG: 2022/11/28 16:02:24.165681 /home/developer/app/cmd/createUtils.go:299: Gitlab ready
LOG: 2022/11/28 16:02:24.166438 /home/developer/app/cmd/createUtils.go:299: waiting for vault unseal
LOG: 2022/11/28 16:02:24.167193 /home/developer/app/cmd/createGitlab.go:233: configuring vault
LOG: 2022/11/28 16:02:24.168237 /home/developer/app/pkg/shell.go:35: INFO: Running /home/developer/.k1/tools/terraform
LOG: 2022/11/28 16:02:24.168915 /home/developer/app/pkg/shell.go:39:  export TF_VAR_gitlab_token = ********************
LOG: 2022/11/28 16:02:24.169394 /home/developer/app/pkg/shell.go:39:  export AWS_SDK_LOAD_CONFIG = *
LOG: 2022/11/28 16:02:24.170012 /home/developer/app/pkg/shell.go:39:  export TF_VAR_aws_region = *********
LOG: 2022/11/28 16:02:24.170681 /home/developer/app/pkg/shell.go:39:  export TF_VAR_vault_token = ****************************
LOG: 2022/11/28 16:02:24.171233 /home/developer/app/pkg/shell.go:39:  export TF_VAR_vault_redirect_uris =
LOG: 2022/11/28 16:02:24.171845 /home/developer/app/pkg/shell.go:39:  export TF_VAR_git_provider = ******
LOG: 2022/11/28 16:02:24.172496 /home/developer/app/pkg/shell.go:39:  export VAULT_ADDR = *********************
LOG: 2022/11/28 16:02:24.172979 /home/developer/app/pkg/shell.go:39:  export AWS_DEFAULT_REGION = *********
LOG: 2022/11/28 16:02:24.173453 /home/developer/app/pkg/shell.go:39:  export TF_VAR_vault_addr = **********************************
LOG: 2022/11/28 16:02:24.173975 /home/developer/app/pkg/shell.go:39:  export TF_VAR_github_token =
LOG: 2022/11/28 16:02:24.174541 /home/developer/app/pkg/shell.go:39:  export TF_VAR_ssh_private_key = *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
LOG: 2022/11/28 16:02:24.175514 /home/developer/app/pkg/shell.go:39:  export TF_VAR_kubefirst_bot_ssh_public_key = *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
LOG: 2022/11/28 16:02:24.176181 /home/developer/app/pkg/shell.go:39:  export AWS_PROFILE = *******
LOG: 2022/11/28 16:02:24.176702 /home/developer/app/pkg/shell.go:39:  export TF_VAR_email_address = *****************
LOG: 2022/11/28 16:02:24.177261 /home/developer/app/pkg/shell.go:39:  export TF_VAR_hosted_zone_name = ********************
LOG: 2022/11/28 16:02:24.177781 /home/developer/app/pkg/shell.go:39:  export TF_VAR_gitlab_runner_token = ****************************************************************
LOG: 2022/11/28 16:02:24.178181 /home/developer/app/pkg/shell.go:39:  export VAULT_TOKEN = ****************************
LOG: 2022/11/28 16:02:24.178614 /home/developer/app/pkg/shell.go:39:  export TF_VAR_aws_account_id = ************
LOG: 2022/11/28 16:02:24.179069 /home/developer/app/pkg/shell.go:39:  export TF_VAR_hosted_zone_id = *********************
LOG: 2022/11/28 16:02:24.179498 /home/developer/app/pkg/shell.go:39:  export TF_VAR_atlantis_repo_webhook_secret = ********************
LOG: 2022/11/28 16:02:24.241237 /home/developer/app/pkg/shell.go:64: OUT:  Initializing modules...
LOG: 2022/11/28 16:02:24.245880 /home/developer/app/pkg/shell.go:64: OUT:  - argo in modules/oidc-client
LOG: 2022/11/28 16:02:24.248380 /home/developer/app/pkg/shell.go:64: OUT:  - argocd in modules/oidc-client
LOG: 2022/11/28 16:02:24.249972 /home/developer/app/pkg/shell.go:64: OUT:  - console in modules/oidc-client
LOG: 2022/11/28 16:02:24.250549 /home/developer/app/pkg/shell.go:64: OUT:  - gitlab in modules/oidc-client
LOG: 2022/11/28 16:02:24.254239 /home/developer/app/pkg/shell.go:70: ERR:  There are some problems with the configuration, described below.
LOG: 2022/11/28 16:02:24.254746 /home/developer/app/pkg/shell.go:70: ERR:
LOG: 2022/11/28 16:02:24.255211 /home/developer/app/pkg/shell.go:70: ERR:  The Terraform configuration must be valid before initialization so that
LOG: 2022/11/28 16:02:24.255715 /home/developer/app/pkg/shell.go:70: ERR:  Terraform can determine which modules and providers need to be installed.
LOG: 2022/11/28 16:02:24.256164 /home/developer/app/pkg/shell.go:70: ERR:  ╷
LOG: 2022/11/28 16:02:24.256790 /home/developer/app/pkg/shell.go:70: ERR:  │ Error: Duplicate required providers configuration
LOG: 2022/11/28 16:02:24.257214 /home/developer/app/pkg/shell.go:70: ERR:  │
LOG: 2022/11/28 16:02:24.258444 /home/developer/app/pkg/shell.go:70: ERR:  │   on oidc-provider.tf line 2, in terraform:
LOG: 2022/11/28 16:02:24.259006 /home/developer/app/pkg/shell.go:70: ERR:  │    2:   required_providers {
LOG: 2022/11/28 16:02:24.259507 /home/developer/app/pkg/shell.go:70: ERR:  │
LOG: 2022/11/28 16:02:24.260359 /home/developer/app/pkg/shell.go:70: ERR:  │ A module may have only one required providers configuration. The required
LOG: 2022/11/28 16:02:24.260811 /home/developer/app/pkg/shell.go:70: ERR:  │ providers were previously configured at main.tf:8,3-21.
LOG: 2022/11/28 16:02:24.261238 /home/developer/app/pkg/shell.go:70: ERR:  ╵
LOG: 2022/11/28 16:02:24.261589 /home/developer/app/pkg/shell.go:70: ERR:
LOG: 2022/11/28 16:02:24.261500 /home/developer/app/pkg/shell.go:77: error: /home/developer/.k1/tools/terraform failed exit status 1
LOG: 2022/11/28 16:02:24.262374 /home/developer/app/internal/vault/vault.go:116: error: terraform init failed exit status 1
LOG: 2022/11/28 16:02:24.262932 /home/developer/app/cmd/create.go:40: [000] Create duration is 23m48.944066713s
```

**Comment by 6za** [comment]
Using `main` gitops templates.

**Comment by 6za** [comment]
Last test showed no issue on creating gitlab, it was address by PR - https://github.com/kubefirst/gitops-template/pull/197
