### ISSUE TITLE
Local - 1.10 readiness check - Error on PF on main/main local install

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#845]
# Overview 

Code on `main` / using template from `main` template is showing the following error for local install:

```bash 
- Waiting for vault to be ready
Send Telemetry                ... 50.0% [##############..............] [1 in 5m17.073789s]
Setup base cluster            ... 50.0% [##############..............] [1 in 5m17.073904s]
Install apps to cluster       ... 50.0% [##############..............] [2 in 5m17.073914s]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1765e85]

goroutine 311 [running]:
github.com/kubefirst/kubefirst/internal/k8s.PortForwardPod(_, {0xc0004f0900, {{{0x0, 0x0}, {0x0, 0x0}}, {{0x1ce8dce, 0x7}, {0x0, 0x0}, ...}, ...}, ...})
	/app/internal/k8s/portForward.go:79 +0x125
github.com/kubefirst/kubefirst/internal/k8s.OpenPortForwardPodWrapper.func1()
	/app/internal/k8s/wrappers.go:154 +0x4d
created by github.com/kubefirst/kubefirst/internal/k8s.OpenPortForwardPodWrapper
	/app/internal/k8s/wrappers.go:153 +0x29d
root@docker-desktop:/app# /app/logs/log_1670590652.log
``` 

- Possible issue with PF

## Cluster state when the error happen
```bash 
kubectl  --kubeconfig ~/k3dconfig get pods -A -w
NAMESPACE                   NAME                                                              READY   STATUS              RESTARTS      AGE
kube-system                 coredns-b96499967-2xsbp                                           1/1     Running             0             7m29s
kube-system                 local-path-provisioner-7b7dc8d6f5-g2j5g                           1/1     Running             0             7m29s
kube-system                 helm-install-traefik-crd-gtjxq                                    0/1     Completed           0             7m30s
kube-system                 helm-install-traefik-m2g8r                                        0/1     Completed           1             7m30s
kube-system                 svclb-traefik-eb3e88ab-4knjd                                      2/2     Running             0             6m37s
kube-system                 svclb-traefik-eb3e88ab-mzsf4                                      2/2     Running             0             6m37s
kube-system                 svclb-traefik-eb3e88ab-2kwdz                                      2/2     Running             0             6m37s
kube-system                 metrics-server-668d979685-7j2mt                                   1/1     Running             0             7m29s
kube-system                 svclb-traefik-eb3e88ab-cl2sh                                      2/2     Running             0             6m37s
kube-system                 traefik-7cd4fcff68-hr7pj                                          1/1     Running             0             6m37s
argocd                      argocd-redis-7df94749bb-bsv5f                                     1/1     Running             0             6m13s
argocd                      argocd-applicationset-controller-77445749f4-5dlws                 1/1     Running             0             6m13s
argocd                      argocd-notifications-controller-d7879d8f8-x8vm7                   1/1     Running             0             6m13s
argocd                      argocd-application-controller-0                                   1/1     Running             0             6m12s
argocd                      argocd-server-67bb46b8bf-kj6zt                                    1/1     Running             0             6m13s
argocd                      argocd-dex-server-58fdd67bb-vkjxp                                 1/1     Running             0             6m13s
argocd                      argocd-repo-server-d778c56c6-58p49                                1/1     Running             0             6m13s
github-runner               actions-runner-contoller-actions-runner-controller-86c4b4dz5q42   0/2     ContainerCreating   0             3m51s
atlantis                    atlantis-0                                                        0/1     ContainerCreating   0             3m50s
vault                       vault-agent-injector-59775cb565-ch4zc                             1/1     Running             0             3m58s
argo                        argo-workflow-controller-6fdfd5dbc-2x5lk                          1/1     Running             0             3m46s
vault                       vault-0                                                           1/1     Running             0             3m58s
cert-manager                cert-manager-cainjector-bbdb88874-rbdrt                           1/1     Running             0             3m56s
cert-manager                cert-manager-webhook-5774d5d8f7-xtkwm                             1/1     Running             0             3m56s
cert-manager                cert-manager-877fd747c-p9hz8                                      1/1     Running             0             3m56s
argo                        argo-server-678dfd9865-stjr6                                      1/1     Running             0             3m46s
external-secrets-operator   external-secrets-operator-64d5cd995d-8227x                        1/1     Running             0             3m42s
minio                       minio-5c749ff764-jcpqn                                            1/1     Running             0             3m58s
kubefirst                   kubefirst-console-6b486cc5b7-nktz4                                1/1     Running             0             3m32s
external-secrets-operator   external-secrets-operator-webhook-7487f9fcd-nz2wn                 1/1     Running             0             3m42s
external-secrets-operator   external-secrets-operator-cert-controller-55f94bb578-jxgzp        1/1     Running             0             3m42s
chartmuseum                 chartmuseum-6f5965d54b-l2rpb                                      1/1     Running             3 (34s ago)   3m45s
```

# logs

```bash 
LOG: 2022/12/09 13:03:20.952473 /app/pkg/shell.go:25: OUT: NAME                                    READY   STATUS              RESTARTS   AGE
vault-0                                 0/1     ContainerCreating   0          60s
vault-agent-injector-59775cb565-ch4zc   1/1     Running             0          60s

LOG: 2022/12/09 13:03:20.952884 /app/pkg/shell.go:26: ERR: 
LOG: 2022/12/09 13:03:20.953468 /app/internal/vault/vault.go:230: vault pods found, continuing
```

# How installation was executed

```bash 
rm ./kubefirst
go build  .
export KUBEFIRST_GITHUB_AUTH_TOKEN='----'
./kubefirst local --gitops-branch main
```

**Comment by 6za** [comment]
Extra info:
```bash 
netstat -an | grep LISTEN
tcp46      0      0  *.59673                *.*                    LISTEN
tcp46      0      0  *.63630                *.*                    LISTEN
tcp6       0      0  *.52712                *.*                    LISTEN
tcp4       0      0  *.52712                *.*                    LISTEN
tcp6       0      0  *.5000                 *.*                    LISTEN
tcp4       0      0  *.5000                 *.*                    LISTEN
tcp6       0      0  *.7000                 *.*                    LISTEN
tcp4       0      0  *.7000                 *.*                    LISTEN
tcp4       0      0  *.19756                *.*                    LISTEN
tcp4       0      0  127.0.0.1.30862        *.*                    LISTEN
tcp4       0      0  127.0.0.1.28196        *.*                    LISTEN
tcp4       0      0  127.0.0.1.17700        *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49162 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49161 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49160 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49159 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49158 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49157 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49156 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49155 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49154 *.*                    LISTEN
tcp6       0      0  fe80::aede:48ff:.49153 *.*                    LISTEN
```

**Comment by 6za** [comment]
Retry logic was added, and that solved the observed issue. If issue still exist, new ticket should be open.
