### ISSUE TITLE
regression - backupoSSL not working on 1.11

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#900]
Error when running `backupSSL`: 

```bash 
developer@68345989daeb:~/app$ ./kubefirst backupSSL
2022/12/14 14:15:20 kubefirst started
Logging at: /home/developer/app/logs/log_1671027320.log
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
panic: erro: error getting resources from k8s: Get "...us-east-1.eks.amazonaws.com/apis/cert-manager.io/v1/namespaces/argo/certificates": getting credentials: exec: executable aws-iam-authenticator failed with exit code 1

goroutine 1 [running]:
log.Panic({0xc000039c00?, 0x1cfe1d0?, 0xc0000036c0?})
	/usr/local/go/src/log/log.go:385 +0x65
github.com/kubefirst/kubefirst/cmd.glob..func7(0x2d529a0?, {0x1ce90c5?, 0x0?, 0x0?})
	/home/developer/app/cmd/backupSsl.go:27 +0x6d
github.com/spf13/cobra.(*Command).execute(0x2d529a0, {0x2d9fdc0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2d51fa0)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
	/home/developer/app/cmd/root.go:37 +0x25
main.main()
	/home/developer/app/main.go:68 +0x585

```

# Logs
```bash
[90m2:15PM[0m [32mINF[0m [1mhelpers.go:348[0m[36m >[0m Using config file: /home/developer/.kubefirst
LOG: 2022/12/14 14:15:20.367393 /home/developer/app/internal/ssl/ssl.go:88: GetBackupCertificates called
LOG: 2022/12/14 14:15:20.368059 /home/developer/app/internal/aws/aws.go:400: createBucketCalled
LOG: 2022/12/14 14:15:20.369854 /home/developer/app/internal/aws/aws.go:415: creating bucket:  k1-kubefirst.tech
LOG: 2022/12/14 14:15:20.370258 /home/developer/app/internal/aws/aws.go:418: region is  us-east-1
LOG: 2022/12/14 14:15:21.307115 /home/developer/app/internal/ssl/ssl.go:101: getting certificates
LOG: 2022/12/14 14:15:21.309411 /home/developer/app/internal/ssl/ssl.go:53: getting resources
LOG: 2022/12/14 14:15:26.924860 /home/developer/app/cmd/backupSsl.go:27: erro: error getting resources from k8s: Get Suppressed...
```

It seems to be related to kubeconfig changes

**Comment by 6za** [comment]
I am not using `default` profile for AWS

**Comment by 6za** [comment]
Issue related to the profile, is not exported and not default it fails. It is not using `.kubefirst` to detect the profile used. 

if exported the profile it will work as workaround. 
```bash 
export AWS_PROFILE=starter
```
